### ISSUE TITLE
Current Version doesn't support IE11

### ISSUE THREAD

**Issue by SchroeerM** [react-dropzone/react-dropzone#994] opened 2020-08-05 06:19 UTC
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Simply open the Link https://react-dropzone.js.org/ in InternetExplorer 11

**What is the expected behavior?**

The Dropzone should be rendered and works as expected.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
React-Dropzone version 11.0.2; Internet Explorer 11.3808

**Comment by arolonger** [comment] 2020-08-07 10:23
I can see similar problem with working on IE11.
Seems like it's a problem with arrow function which wasn't transpiled:
![image](https://user-images.githubusercontent.com/19307025/89636376-d05bbd80-d8a8-11ea-8c9b-611be449350b.png)

**Comment by JiriLojda** [comment] 2020-08-17 16:02
I have the same problem. It seems to be caused by using es6 version of the attr-accept package. I fixed it by altering my Webpack configuration to use the es5 version.
`alias: {
        'attr-accept$': 'attr-accept/dist',
      }`

**Comment by SchroeerM** [comment] 2020-09-02 13:36
I don't use webpack in my current solution and wanted to keep the project as small as possible. So its a major point for us to go further with implementing the dropzone in the project. If theres no other possibility to fix this issue we have to remove the dropzone.

**Comment by rolandjitsu** [comment] 2020-09-05 12:17
It's possible this was fixed with https://github.com/react-dropzone/attr-accept/commit/5275b006fadb3607d0e3ca5bd9014e3fab00b29b. Could you check what version of attr-accept you have? And if it's not fixed, you can just move this issue there.

**Comment by rolandjitsu** [comment] 2020-11-07 10:23
@SchroeerM could you confirm whether the update I mentioned above fixed this issue or not?

**Comment by arolonger** [comment] 2020-11-17 10:35
I can confirm that after update react-dropzone to 11.2.4 problem dissapear.
I've used workaroud:
alias: { 'attr-accept$': 'attr-accept/dist', }

but it's not needed anymore.

@SchroeerM - please confirm so we could close and keep issues section clear.

**Comment by rolandjitsu** [comment] 2020-11-22 08:59
I will close this for now. If the issue persists, we'll move it to the attr-accept lib.

**Closed by rolandjitsu** 2020-11-22 08:59 UTC
