### ISSUE TITLE
[BUG] TS2322: Type 'string | { "image/*": string[]; }' is not assignable to type 'Accept'

### ISSUE THREAD

**Issue by khteh** [react-dropzone/react-dropzone#1229] opened 2022-08-25 08:56 UTC
**Describe the bug**
"react-dropzone": "^14.2.2"
```
 const { getRootProps, getInputProps, isDragActive } = useDropzone({
    accept: {
      "image/*": [".jpeg", ".png", ".jpg"],
    },
```
Error:
```
MediaField.tsx:266:5 - error TS2322: Type 'string | { "image/*": string[]; }' is not assignable to type 'Accept'.
  Type 'string' is not assignable to type 'Accept'.

266     accept: {
        ~~~~~~

  node_modules/react-dropzone/typings/react-dropzone.d.ts:31:3
    31   accept?: Accept;
         ~~~~~~
    The expected type comes from property 'accept' which is declared here on type 'DropzoneOptions'
```
What do I miss?
**To Reproduce**

3. Select file '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AuthorProxy** [comment] 2022-08-26 14:55
can you add codepen for this example, looks like you post modified code

**Comment by khteh** [comment] 2022-08-27 04:42
What do you mean? I don't use codepen. This is the content of `node_modules/read-dropzone/typings/react-dropzone.d.ts`:
```
import * as React from "react";

export { FileWithPath } from "file-selector";
export default function Dropzone(
  props: DropzoneProps & React.RefAttributes<DropzoneRef>
): JSX.Element;
export function useDropzone(options?: DropzoneOptions): DropzoneState;

export interface DropzoneProps extends DropzoneOptions {
  children?(state: DropzoneState): JSX.Element;
}

export enum ErrorCode {
  FileInvalidType = "file-invalid-type",
  FileTooLarge = "file-too-large",
  FileTooSmall = "file-too-small",
  TooManyFiles = "too-many-files",
}

export interface FileError {
  message: string;
  code: ErrorCode | string;
}

export interface FileRejection {
  file: File;
  errors: FileError[];
}

export type DropzoneOptions = Pick<React.HTMLProps<HTMLElement>, PropTypes> & {
  accept?: Accept;
  minSize?: number;
  maxSize?: number;
  maxFiles?: number;
  preventDropOnDocument?: boolean;
  noClick?: boolean;
  noKeyboard?: boolean;
  noDrag?: boolean;
  noDragEventsBubbling?: boolean;
  disabled?: boolean;
  onDrop?: <T extends File>(
    acceptedFiles: T[],
    fileRejections: FileRejection[],
    event: DropEvent
  ) => void;
  onDropAccepted?: <T extends File>(files: T[], event: DropEvent) => void;
  onDropRejected?: (fileRejections: FileRejection[], event: DropEvent) => void;
  getFilesFromEvent?: (
    event: DropEvent
  ) => Promise<Array<File | DataTransferItem>>;
  onFileDialogCancel?: () => void;
  onFileDialogOpen?: () => void;
  onError?: (err: Error) => void;
  validator?: <T extends File>(file: T) => FileError | FileError[] | null;
  useFsAccessApi?: boolean;
  autoFocus?: boolean;
};

export type DropEvent =
  | React.DragEvent<HTMLElement>
  | React.ChangeEvent<HTMLInputElement>
  | DragEvent
  | Event;

export type DropzoneState = DropzoneRef & {
  isFocused: boolean;
  isDragActive: boolean;
  isDragAccept: boolean;
  isDragReject: boolean;
  isFileDialogActive: boolean;
  acceptedFiles: File[];
  fileRejections: FileRejection[];
  rootRef: React.RefObject<HTMLElement>;
  inputRef: React.RefObject<HTMLInputElement>;
  getRootProps: <T extends DropzoneRootProps>(props?: T) => T;
  getInputProps: <T extends DropzoneInputProps>(props?: T) => T;
};

export interface DropzoneRef {
  open: () => void;
}

export interface DropzoneRootProps extends React.HTMLAttributes<HTMLElement> {
  refKey?: string;
  [key: string]: any;
}

export interface DropzoneInputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {
  refKey?: string;
}

type PropTypes = "multiple" | "onDragEnter" | "onDragOver" | "onDragLeave";

export interface Accept {
  [key: string]: string[];
}
```

**Comment by AuthorProxy** [comment] 2022-08-30 11:16
I mean add example to reproduce plz, if you don't use it - start do it ) It will help to test a possible bug in isolated environment. You  can take a base template in codepen with react-dropzone and modify it to show where you meet a problems

**Comment by devalnor** [comment] 2022-10-13 13:40
+1

**Comment by gayancharith** [comment] 2022-11-23 06:59
+1

**Comment by Eerik001** [comment] 2022-11-29 12:24
+1

**Comment by Muhindo-Galien** [comment] 2022-12-18 14:58
use the code bellow instead
 accept: {
      'image/png': ['.jpg'],
      'text/html': ['.html', '.htm'],
    },


@khteh

**Comment by rolandjitsu** [comment] 2024-10-03 20:13
Closing this as it seems like ppl found the solution.

**Closed by rolandjitsu** 2024-10-03 20:13 UTC
Labels: bug
