### ISSUE TITLE
When hover on preview at that time text is display 

### ISSUE THREAD

**Issue by parthsavaliya1** [react-dropzone/react-dropzone#1209] opened 2022-06-20 04:15 UTC
**Describe the bug**
after image upload when hover on preview at that time text is display

**To Reproduce**
1. Upload image
2. hover on preview
3. check text is display

**Expected behavior**
when hover on preview text should not be display

**Screenshots**
https://share.vidyard.com/watch/ADPMZYvbwo2aDK7fPAstHW?

**Desktop (please complete the following information):**
 - OS: Window
 - Browser chrome

**Smartphone (please complete the following information):**

**Comment by rolandjitsu** [comment] 2022-07-03 02:17
@parthsavaliya1 you'll have to provide more context and info. With the current description I'm not sure I follow what the issue is.

**Comment by rolandjitsu** [comment] 2024-10-03 19:58
No feedback provided, so closing this.

**Closed by rolandjitsu** 2024-10-03 19:58 UTC
Labels: bug
