### ISSUE TITLE
Failure to attach image directly from camera

### ISSUE THREAD

**Issue by wolfgangmeyers** [react-dropzone/react-dropzone#945] opened 2020-03-22 20:06 UTC
**Do you want to request a *feature* or report a *bug*?**

- [ X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When I attach an image directly from my phone's camera, I see an error that the operation could not be completed due to running out of memory. If I instead select an image that was previously captured from the camera, everything works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Navigate to https://codesandbox.io/s/01kw5vw840
1. Tap on the dropzone on the top
1. Take a photo with the camera
1. Confirm the image
1. The page will reload and display an error "Unable to complete previous operation due to low memory"

**What is the expected behavior?**
The image should be loaded into the dropzone with no errors or page reload

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
This is on a samsung galaxy note 9 with android on the Chrome browser. This happens on react-dropzone version 10.2.1.

**Comment by wolfgangmeyers** [comment] 2020-03-22 20:09
I tried this with the samsung browser, and the behavior is the same, except that no error message is displayed.

**Comment by rwilcox3** [comment] 2020-04-17 15:51
I tried this using drag and drop split screen on Android using the provided example and the built-in files app and also was not able to get this to work.  Seems the drop is not being processed on android

Steps to recreate:
1)  Navigate to https://codesandbox.io/s/01kw5vw840
2) Open Files App on Android
3) Split Screen the browser (I used chrome) and the files app.
4) Drag and drop an image file onto the browser.  Nothing happens.

**Comment by wolfgangmeyers** [comment] 2020-06-22 13:41
It's still a problem, @stalebot!

**Comment by scooterlord** [comment] 2020-11-20 21:34
Still a problem!

**Comment by Anto-Farrell** [comment] 2021-02-12 22:50
Still a problem, I downloaded the newest drozone.js & still have the same problem. Pictures taken by camera via drozone get broken therefor nothing gets uploaded, if I take pictures with my camera outside dropzone & then upload it via dropzone, images upload successfully with no problems.

**Comment by rolandjitsu** [comment] 2021-02-16 00:36
> Still a problem, I downloaded the newest drozone.js & still have the same problem. Pictures taken by camera via drozone get broken therefor nothing gets uploaded, if I take pictures with my camera outside dropzone & then upload it via dropzone, images upload successfully with no problems.

What device are you using? Is it Android or iOS? Which version of OS? Which browser?

**Comment by Anto-Farrell** [comment] 2021-02-20 05:12
This happens on all the devices I have, 
Samsung Galaxy s5: Android Ver. 8.0.0
Moto e5 Plus: Android Ver. 8.0.0
iPad 4, all using chrome latest version
I created a website in 2017 & used dropzone, it worked marvelously in any device I had back then, I have 10 backups of my finished website & no matter what backup I use dropzone fails to functions in all of my devices right now, everything works as epected EXCEPT drozone & I haven't touched the code since it last worked properly.

**Comment by rolandjitsu** [comment] 2021-02-23 03:26
@Anto-Farrell ok, thanks. We'll need to look into this. If you can help, we'd appreciate it, otherwise this might take some time to fix.

**Comment by rolandjitsu** [comment] 2021-03-26 08:15
Sorry guys, I didn't have much time to look into this. Did any of you manage to make any progress in finding out why it's happening?

**Comment by morijenab** [comment] 2021-03-26 16:44
I have tried this issue (provided the example on the official doc) haven't seen any error.
chrome ver: 88.0.4324.152
Samsung internet browser ver:  13.2.3.2
Android 9 SM-J730F

**Comment by beingtmk** [comment] 2021-03-31 21:16
faced the same problem both on android(chrome) and ios(safari).

**Comment by AditiTrehan** [comment] 2021-05-20 13:59
Updated the package version to the latest one - **11.3.2**, and it fixed the problem.

**Comment by cderickstudy** [comment] 2021-06-10 14:28
Maybe due the attribute 'capture' <input capture /> on the input, do not trigger the onDrop event?

I'm face similar issue but I will check if update for the latest version will solve the problem, per the last comment. :)

**Comment by cderickstudy** [comment] 2021-06-10 16:48
Okay digging in my problem...
My issue was regarding on the upload by Take a photo, the file reader for some reason do not convert perfect the picture in Base64.

If you upload or drop the file, FileReader will convert perfectly, if you take a picture direct from the Camera it doesn't work. 
Might be the issue with base64 on safari need to be divisible by 4.

11.3.2 is working normally.
If the issue is due a conversion using FileReader, so the problem is not react-dropzone.

**Comment by rolandjitsu** [comment] 2022-02-02 05:07
I'm on Android 12 on a Pixel 3 and the current docs site (which is on react-dropzone v11.5) seems to work w/o issues.

https://user-images.githubusercontent.com/1479737/152096064-605940a1-f218-4082-bd30-fac17ba31132.mp4

**Comment by Anto-Farrell** [comment] 2022-06-06 09:10
I think I've figured it out, the problem was the file size
This helped me fix the problem: https://stackoverflow.com/questions/2184513/change-the-maximum-upload-file-size
Basically I just had to create a php.ini file on my website and add this: 
upload_max_filesize = 10M
post_max_size = 10M
Files size is set to 10 Megabytes. Apparently pictures taken by camera are larger than 2 megabytes which is the default file size php.ini is set to.

**Comment by ivanebhtpicha** [comment] 2022-11-17 11:45
I still have this issue, and I've updated to the last version

**Comment by dashty94** [comment] 2023-08-30 10:26
After debugging this for too long, I've figured that the issue has nothing to do with this library. You would face the same issue even with using the native HTML file uploading.

It is a common issue in Android devices that try to maintain the memory management of the applications that are in the background. When trying to take a picture from the device's camera, it puts the browser in background causing the issue occasionally.

More detail here: https://stackoverflow.com/a/38191559

Personally, as a workaround, I instead implemented an in-browser camera API and allowed them to capture images directly there without switching to the camera app.

**Comment by rolandjitsu** [comment] 2024-10-03 19:41
I'm gonna go ahead and close this for now. I'd be happy to re-open if there's something we can do on our end.

**Closed by rolandjitsu** 2024-10-03 19:41 UTC
Labels: help wanted, needs investigation
