### ISSUE TITLE
Document website is not running

### ISSUE THREAD

**Issue by DeepakM02** [react-dropzone/react-dropzone#892] opened 2019-10-16 05:37 UTC
bundle.21ea12b5.js:13 Uncaught TypeError: Cannot read property 'F' of undefined

Got this error when try to run this url   [https://react-dropzone.js.org/](https://react-dropzone.js.org/)

**Comment by rolandjitsu** [comment] 2019-10-16 05:38
Duplicate of https://github.com/react-dropzone/react-dropzone/issues/887.

**Closed by rolandjitsu** 2019-10-16 05:38 UTC
