### ISSUE TITLE
Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string

### ISSUE THREAD

**Issue by kambing86** [react-dropzone/react-dropzone#1088] opened 2021-08-24 04:07 UTC
value for HTMLInputElement shouldn't set to null, but this happened to

https://github.com/react-dropzone/react-dropzone/blob/4e625d27410cb7a1b0703b2997142e65a89a78d9/src/index.js#L426

**Comment by rolandjitsu** [comment] 2021-08-25 03:35
@kambing86 can you provide a code sandbox link to replicate this?

**Comment by rolandjitsu** [comment] 2021-09-14 00:02
@kambing86 gonna close this as the issue is not following the required template. If it's still valid, please reopen and provide a proper example illustrating the issue.

**Closed by rolandjitsu** 2021-09-14 00:02 UTC

**Comment by MisiM** [comment] 2024-10-21 17:27
I had the same error and not setting the value attribute on the input element fixed the error.
_In React, an <input type="file" /> is always an uncontrolled component because its value can only be set by a user, and not programmatically._
This is a security feature, to ensure that you can not pull data from a users disk without them specifically choosing to do so.
