### ISSUE TITLE
file.path is undefined

### ISSUE THREAD

**Issue by anthonyraymond** [react-dropzone/react-dropzone#477] opened 2017-08-07 22:48 UTC
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [ ] I want to propose a feature
- [x] improve documentation

**What is the current behavior?**
The plugin 'looks' broken in recent browsers. We can't access `file.path`
![2017-08-08 00_04_18-joal ui - development build](https://user-images.githubusercontent.com/7503585/29047883-42570650-7bce-11e7-89ec-def731ece434.png)

**If this is a feature request, what is motivation or use case for changing the behavior?**

Browsers are **hidding file path** intentionally for security purpose.
If you want to access file content (don't bother trying to get the path, you can't get it). Use the [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) like so:

```es6
const reader = new FileReader();
reader.onload = () => {
  const fileAsBinaryString = reader.result;
 // do whatever you want with the file content
};
reader.onabort = () => console.log('file reading was aborted');
reader.onerror = () => console.log('file reading has failed');

reader.readAsBinaryString(file);
```
This sample uses es6 syntax and filereader api to read file content.
`readAsBinaryString`is not the only method available, check the link above.

<br />
I think this should be added to the readme and the example should be updated as well.
<br /><br />

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
react-dropzone 3.13.3 and 4.0.0
Google Chrome: 60.0.3112.90
OS: Windows

**Comment by okonet** [comment] 2017-08-17 12:28
I'm not sure what you're proposing exactly but I think this is a duplicate of #459

**Comment by anthonyraymond** [comment] 2017-08-17 12:32
I was asking if you could add an example of filereader api in the readme. Because new browsers version dont set the property `path` on file objects anymore

**Comment by okonet** [comment] 2017-08-17 12:38
I'm not sure how this example will help solving the issue. Some Dropzone functionality relies on `file.path` and might not work properly. See linked issue.

If you want to add something the README, please send me a PR.

**Comment by anthonyraymond** [comment] 2017-08-17 13:25
Actually it's not really for solving anything.

in my application, i need to read the content of dropped files, and on previous browsers version i was using [fs.readFileSync(file.path)](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options) to access file content.
But new versions prevent usage of `file.path` (probably for security reasons), so the new solution to access file's content is to use the [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader).

The issue was more about adding a warning in the readme that file should be accessed with filereader API in the `onDrop()` callback.

Not sure i could open a PR soon, but i'll try to do when i'll get some time.

**Comment by anthonyraymond** [comment] 2017-08-18 08:20
@okonet Just created a PR #481

**Closed** 2017-08-18 08:25 UTC
