### ISSUE TITLE
[BUG] cannot open file dialog on wechat-miniprogram on Android phone

### ISSUE THREAD

**Issue by lzgdnh** [react-dropzone/react-dropzone#1212] opened 2022-06-28 03:09 UTC
**Describe the bug**
Cannot open file dialog on wechat-miniprogram on Android phone, it works on desktop, web app, wechat-miniprogram on IOS phone.

**To Reproduce**
open wechat-miniprogram on Android phone
click upload element,
it cannot open file dialog, also no error in onError callback. 

**Expected behavior**
it can open file dialog

**Screenshots**
this page is in webview
![image](https://user-images.githubusercontent.com/12907912/176082664-d03e2e99-801b-4b14-83cf-1b24e152cad1.png)
![image](https://user-images.githubusercontent.com/12907912/176082792-dce4295c-4e5b-4aa3-b580-3b75d66c3ba9.png)

**Smartphone (please complete the following information):**
 - Device: Xiao Mi 11 pro
 - OS: Android 13
 - Browser : wechat miniprogram
 - Version 8.0.23

**Comment by rolandjitsu** [comment] 2022-07-03 02:20
Gonna need a link to some code so we can run it to see what the issue is. I cannot really tell what the issue is just from the description and I have no way to reproduce on the device you've referenced.

**Comment by rolandjitsu** [comment] 2024-10-03 20:01
I'm going to close this since there was no feedback from the author.

**Closed by rolandjitsu** 2024-10-03 20:01 UTC
Labels: bug
