### ISSUE TITLE
`onFileDialogCancel` doesn't seem to be firing.

### ISSUE THREAD

**Issue by Sburke0708** [react-dropzone/react-dropzone#575] opened 2018-02-24 20:37 UTC
I'm adding `onFileDialogCancel` like so:

```                    
<Dropzone
    name="rightNorth"
    multiple
    onFileDialogCancel={() => console.log('test')}
>
...
</Dropzone>
```

However I'm not receiving the callback when I cancel the dialog. Is this feature working? I'm using version 4.2.5

**Comment by carmouche** [comment] 2018-03-14 02:03
I'm seeing the same issue in 4.2.9

**Comment by gregorianisch** [comment] 2018-03-16 12:20
Same here, please fix asap if possible. Thanks!

**Comment by okonet** [comment] 2018-03-16 12:30
Please submit a PR if you want this to be fixed.

**Comment by viniciusdacal** [comment] 2018-03-16 14:01
this and #557 are related. Will try to open a PR with the fix.

**Comment by jaredkirkley** [comment] 2018-05-16 13:42
bump

**Comment by okonet** [comment] 2018-05-17 06:43
Ideally we’d have a PR to close this instead of keeping it around.

**Closed** 2018-05-22 18:32 UTC

**Comment by Tomisiak** [comment] 2018-09-13 11:03
Looks like this issue still appears in Firefox browser on Windows and Mac OS. Tested on latest version.

**Comment by brackebusch** [comment] 2019-05-16 16:06
This is indeed still a bug. With Firefox the `onFileDialogCancel` is not fired until after you click away from the window and click back in.

**Comment by rolandjitsu** [comment] 2019-05-17 01:47
The way this cb works is that it listens to window focus, so it's possible that it might not be working as expected. But it would be much easier if someone created a simple example illustrating the issue.

**Comment by krnlde** [comment] 2019-05-28 10:08
If you connect a `<label>` through its `for` attribute with the `<input type="file" />` this bug reliably reproduces. Also we have trouble getting it to work on any iPad.

Here:
```jsx
<Dropzone
  onDropAccepted={this.handleDrop}
  onFileDialogCancel={() => this.props.toggleFileDialog(false)}
  onDrop={() => this.props.toggleFileDialog(false)}
>
  {({ getRootProps, getInputProps, isDragActive }) => {
    return (
      <label {...getRootProps()}>
        <input
          {...getInputProps({
          onClick: () => this.props.toggleFileDialog(true),
          id: 'file-upload',
          })}
        />
        Everything works fine when clicking here
      </label>
    );
  }}
</Dropzone>
<label for="file-upload">--------- Click here for bug ---------</label>
```

**Comment by brackebusch** [comment] 2019-05-28 18:09
Add this line to a Dropzone and watch console in Chrome vs Firefox (on Mac) to see difference: `onFileDialogCancel={() => console.log('onFileDialogCancel called')}` Works in Chrome, requires navigating away from window and back in Firefox. Works on Safari when tested.

**Comment by brackebusch** [comment] 2019-06-05 21:56
`onCancelPressed` function more research:

1. does not ever get fired in Firefox unless navigating away from browser and back to it (click on a different application or desktop)
2. fires in Chrome when uploading a file **or** closing file uploader with cancel button
3. is fired in Safari with cancel button, but **not** when a file is uploaded.

**Comment by caseprince** [comment] 2019-10-14 19:44
Bump! - This caused a bug for our app. Windows 10, FF 69.0.3 (64-bit). We've come up with a workaround that increments a counter to trigger `open()` vs toggling a boolean.
