### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by paschalidi** [react-dropzone/react-dropzone#887] opened 2019-10-06 14:13 UTC
**Do you want to request a *feature* or report a *bug*?**

- I found a bug

**What is the current behavior?**

The website is currently down. https://react-dropzone.js.org/ I dont know where is being hosted. Let me know if I can help, I would gladly do so!

**Comment by rolandjitsu** [comment] 2019-10-07 01:20
Thanks for reporting it. Must be due to 4644e8e7a6c767c5f23721f503f587e57288515f. I will investigate more later today or tomorrow.

**Comment by Alek-S** [comment] 2019-10-09 02:48
console error:

```
Uncaught TypeError: Cannot read property 'F' of undefined
    at f (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at bundle.21ea12b5.js:13
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at __webpack_require__ (bundle.21ea12b5.js:1)
```

**Comment by DanielRuf** [comment] 2019-10-09 12:07
Can we try ZEIT Now for PRs and commits so we can directly see the changes?

This would catch such issues much earlier.

**Comment by DanielRuf** [comment] 2019-10-09 12:08
I will try to bisect it.

**Comment by DanielRuf** [comment] 2019-10-09 12:27
Where can we find the needed steps and code to create this page?

**Comment by rolandjitsu** [comment] 2019-10-10 12:06
@DanielRuf there is no page. It's generated from the readme files using [react-styleguidist](https://react-styleguidist.js.org/). The issue is most likely with the react/react-dom dependency being updated. I don't have time at the moment to investigate, but looking into updating react-styleguidist is a good idea.

**Comment by DanielRuf** [comment] 2019-10-10 12:37
At least the normal `build` script started it without any issues. Not sure if I was on the right page. But there might be a difference between dev and prod and peer dependencies (I've used the newest).

**Comment by alexking** [comment] 2019-10-10 16:45
For me doing a `npx styleguidist build` makes a site with that `F` error, but running it as a dev server works fine, oddly. 

So I guess if you need to reference the documentation while the site is down, checkout the project and run `npx styleguidist server` to get it running on 8080.

**Comment by rolandjitsu** [comment] 2019-10-12 04:49
Opened https://github.com/styleguidist/react-styleguidist/issues/1444. I will investigate further meanwhile.

**Comment by rolandjitsu** [comment] 2019-10-16 05:39
Found the issue. Just waiting on https://github.com/react-dropzone/attr-accept/issues/34 to be fixed.

**Comment by Rantelo** [comment] 2019-10-17 15:40
Any updates on the site being down?
Is there something I can do to help?

**Comment by awolfe76** [comment] 2019-10-18 13:05
Is there another way to look at the documentation in the meantime?

**Comment by Alek-S** [comment] 2019-10-18 13:11
@awolfe76 The readme contains the same information as the site, so that can still be used for the time being: [Link](https://github.com/react-dropzone/react-dropzone/blob/master/README.md)

**Comment by awolfe76** [comment] 2019-10-18 13:22
Sorry about that. I was just assuming the site had more detail.
Thanks!

**Comment by rolandjitsu** [comment] 2019-10-19 01:16
The docs are generated from the main readme and from the [examples](https://github.com/react-dropzone/react-dropzone/tree/master/examples).

**Comment by blackr1234** [comment] 2019-10-24 02:44
> @awolfe76 The readme contains the same information as the site, so that can still be used for the time being: [Link](https://github.com/react-dropzone/react-dropzone/blob/master/README.md)

I think the site has more examples than the readme IIRC.

**Comment by zirho** [comment] 2019-11-02 20:39
meanwhile, try things out here
https://codesandbox.io/s/upbeat-butterfly-s8s23

**Comment by Rain120** [comment] 2019-11-05 10:29
The website is updated at **[here](https://react-dropzone-uploader.js.org/docs/examples)** ! 😁😁

**Comment by blackr1234** [comment] 2019-11-05 10:34
> The website is updated at **[here](https://react-dropzone-uploader.js.org/docs/examples)** ! 😁😁

Is this another library?
It's named React Dropzone **Uploader** instead of React Dropzone.

**Comment by Rain120** [comment] 2019-11-05 10:43
@blackr1234 yep, my fault

**Comment by TonyaQi** [comment] 2019-11-12 14:25
I thought the web was down again

**Comment by p12y** [comment] 2019-11-13 02:58
It can be fixed by upgrading react-styleguidist. I tried to make a PR, but it seems I don't have access to the project. Keen to get involved with the the project if you're open to it!

**Comment by DanielRuf** [comment] 2019-11-13 08:17
> but it seems I don't have access to the project

Which project? This repo?

**Comment by p12y** [comment] 2019-11-13 11:28
Ah, my mistake. I've made a pull request with the change.

**Closed** 2019-11-16 11:28 UTC
