### ISSUE TITLE
[BUG] DropzoneArea no longer works with large files

### ISSUE THREAD

**Issue by lidiahhhh** [react-dropzone/react-dropzone#1357] opened 2024-06-04 14:01 UTC
Error code:
message: "The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired."
name: "NotReadableError"

when i try to upload files greater than 2 GB.
If i upload ligther file it works.

This is my code snippet
<DropzoneArea
                    className="dropzone"
                    dropzoneText={t('addvideo.dropvideo', { ns: 'videos' })}
                    onChange={handleVideoUpload}
                    filesLimit={1}
                    acceptedFiles={['video/*']}
                    maxFileSize={5000000000} //5GB
/>

**Comment by rolandjitsu** [comment] 2024-11-01 12:11
@lidiahhhh this is unlikely an issue with this lib and instead an issue with the browser (or a limitation).

**Comment by rolandjitsu** [comment] 2024-11-03 11:49
Gonna go ahead and close this for now as I cannot reproduce with the current summary. We can reopen in case the issue comes back and we have a more comprehensive summary that makes it easy to reproduce.

Note that it may also be related to using the file system access API which would complain about permissions if the file is in a place that the browser doesn't have permissions to access.

**Closed by rolandjitsu** 2024-11-03 11:49 UTC
Labels: bug

**Comment by giuseppeagostini-hotmart** [comment] 2025-03-24 16:53
@rolandjitsu  I'm also having this problem. How can we get around this?
