### ISSUE TITLE
Chrome on iPhone iOS 11 crashes after undoing file selection

### ISSUE THREAD

**Issue by stefanocastriotta** [react-dropzone/react-dropzone#664] opened 2018-09-11 09:28 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug

**What is the current behavior?**
Chrome on iPhone iOS 11 chrashes if i undo file selection after tapping on a dropzone area. Tested from the official example page (https://react-dropzone.js.org/#!/Basic%20example) and the last version of both Chrome (69.0.3497.71) and iOS (11.4.1).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Tap on the dropzone area
2. Choose "Browse" from the Menu
3. Tap on "Cancel" on top right

Here are some screenshots to reproduce the issue:

Step 2:
![screen 1](https://user-images.githubusercontent.com/7884658/45350914-39e7ca00-b5b5-11e8-89b4-5a533dbe76b6.png)

Step 3:
![screen 2](https://user-images.githubusercontent.com/7884658/45350922-3b18f700-b5b5-11e8-9797-010e6611b91d.png)

And then, after tapping on Cancel, the tab crashes and must be closed:
![screen 3](https://user-images.githubusercontent.com/7884658/45350927-3ce2ba80-b5b5-11e8-8829-3a656598052c.png)

**Comment by rolandjitsu** [comment] 2018-12-04 11:49
Closing this as I cannot reproduce.

**Closed by rolandjitsu** 2018-12-04 11:49 UTC
