### ISSUE TITLE
Dropzone responds slowly on firefox with big files

### ISSUE THREAD

**Issue by vilvaq** [react-dropzone/react-dropzone#1043] opened 2021-02-04 07:56 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

When dragging files on Firefox  the component responds with a delay. The delay seems to be directly related to the total size of the files dragged. 

It is reproducible on the components present on the documentation page.

**Steps to reproduce**

1. Open a file manager window and select a group of files that add up to a big size (around 50mb creates a long delay)
2. Drag them over the react-dropzone component
3. You have to wait for a few seconds until the cursor changes, and the component acknowledges the drag via the isDragActive prop
4. Once "loaded" and without releasing you can enter/leave the dropzone with inmediate feedback, without delay

**What is the expected behavior?**

Expected the component to acknowledge the drag instantly like it does in Chrome, no matter the size of the files.

Tested in Mozilla Firefox for Ubuntu 85.0 (64bit)

**Comment by rolandjitsu** [comment] 2021-02-08 06:37
@vilvaq have you tried just making a simple drag 'n' drop zone without this lib (bind the `ondrag`, `ondrop` events to some div) to check if the issue is due to react-dropzone?

**Comment by vilvaq** [comment] 2021-02-08 07:41
Hi @rolandjitsu I just tried what you suggest using the onDragEnter event, and it works perfectly. So I assume, the problem is due to react-dropzone.

You can test it in the examples on react-dropzone's documentation too, it's also replicable there.

**Comment by rolandjitsu** [comment] 2021-02-09 05:46
> Hi @rolandjitsu I just tried what you suggest using the onDragEnter event, and it works perfectly. So I assume, the problem is due to react-dropzone.
> 
> You can test it in the examples on react-dropzone's documentation too, it's also reproducible there.

Ok, got it. We'll need to look into it, but it's most likely due to the async processing that we do to support folders.

**Comment by vilvaq** [comment] 2021-02-09 09:27
Cool. Would love to help you fix it, can you please point me in the general direction on where to look for it?

**Comment by rolandjitsu** [comment] 2021-02-09 09:39
> Cool. Would love to help you fix it, @rolandjitsu can you please point me in the general direction on where to look for it?

Great!

First thing I would try is to replace the default `getFilesFromEvent` (see [docs](https://react-dropzone.js.org/#section-extending-dropzone)) fn with one that does nothing besides just returning the files. If it's not slow anymore, then I'd look at [file-selector](https://github.com/react-dropzone/file-selector) where all the funky file processing (well, it's more like calling some File APIs that might be slow, but there's no processing of the data per say) logic goes on.

**Comment by vilvaq** [comment] 2021-02-12 13:23
@rolandjitsu 

Did more tests using a 2gb file.

It is not happening using Firefox 85.0.2 (64-bit) using MACOSX Mojave 10.14.6

So maybe it is just a Linux thing? I can confirm it happens on Ubuntu 18.04 but dunno about other system configs.

**Comment by rolandjitsu** [comment] 2021-02-16 00:34
> @rolandjitsu
> 
> Did more tests using a 2gb file.
> 
> It is not happening using Firefox 85.0.2 (64-bit) using MACOSX Mojave 10.14.6
> 
> So maybe it is just a Linux thing? I can confirm it happens on Ubuntu 18.04 but dunno about other system configs.

Yeah, I've tried on macOS Catalina, Chrome, and I couldn't replicate it. So it might just be on Ubuntu, but we need to confirm it.

**Comment by vilvaq** [comment] 2021-02-16 07:22
I can confirm it also doesn't happen on Firefox nor Chrome under Windows.

**Comment by rolandjitsu** [comment] 2021-03-26 08:08
Ok, so this may be an issue with the Firefox version for Ubuntu. I suggest reporting this to the Firefox team. I'm not sure we can do anything to prevent that, so I will close this issue for now. If you do get any feedback on this and it turns out we can do something about it, please feel free to open a new issue with the suggestion or make a PR.

**Closed by rolandjitsu** 2021-03-26 08:08 UTC
