### ISSUE TITLE
After adding "activeClassName" and "acceptClassName" props, class names not changing

### ISSUE THREAD

**Issue by goonerDp** [react-dropzone/react-dropzone#677] opened 2018-10-03 10:20 UTC
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug

**What is the current behavior?**
I've added to Dropzone component custom "className", "activeClassName" and "acceptClassName" props. When I drug a valid file over dropzone, no classes are added.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add custom "className", "activeClassName" and "acceptClassName" props.
1. Drag a file over dropzone.
1. Look at Dropzone component classnames change.

**What is the expected behavior?**
Classes are added, as in 5.1.1 version.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Win10
Chrome latest
"react": "16.5.2",
"react-dropzone": "5.1.1"

**Comment by robjtede** [comment] 2018-10-03 13:59
I am experiencing this regression after upgrading to v6.0.1.

**Comment by robjtede** [comment] 2018-10-03 14:12
Probably related to #676

**Comment by robjtede** [comment] 2018-10-04 19:44
sorted in v6.0.2

**Comment by rolandjitsu** [comment] 2018-10-10 12:38
Closing this as it seems to be fixed. Reopen if the issue persists.

**Closed by rolandjitsu** 2018-10-10 12:38 UTC

**Comment by paolavness** [comment] 2020-02-14 04:34
I'm experiencing this issue using on `react 16.9` and `react_dropzone 10.2.1`. Neither `activeClassName` nor `acceptClassName` are having any effect.

`render()` code returns:
```
                <div>
                    <Dropzone onDrop={this.handleOnDrop} >

						{({getRootProps, getInputProps}) => (
							<div {...getRootProps({
								activeClassName: 'uploader-thumb-dragover',
								acceptClassName: 'uploader-thumb-dragover',
								className: 'uploader-thumb',
                        		disablePreview: true,
								onClick: dismissMessage, 
								})}>
								<input {...getInputProps()} />
								<div className="uploader-thumb-face">
									<i className="fal fa-cloud-upload fa-6x" />
									<span>
										<u>{I18n.get('Drop or Select file')}</u>
									</span>
								</div>
							</div>

							)}


                    </Dropzone>
                </div>
```
