### ISSUE TITLE
[BUG] Dropzone not working when hosted on pc's ip instead of localhost

### ISSUE THREAD

**Issue by kodobrody** [react-dropzone/react-dropzone#1251] opened 2022-11-13 01:52 UTC
**Describe the bug**
So I wanted to test my site on a mobile. I'm using next.js.
So I've put `yarn dev -H here.my.ip.address`.
However button that works flawlessly on localhost does not work when I host directly on pc's ip.
Console is not saying anything. It does not work neither on PC I host on nor on mobile.
Button is being clicked correctly, however no action is done.
I thought that maybe it's because of no https, however simple `<input type="file" />` worked perfectly.

**To Reproduce**
I don't believe I can reproduce behavior due to nature of this problem

**Expected behavior**
Button should open file picker

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Browser chrome/firefox
 - Version 107/106

**Smartphone (please complete the following information):**
 - Device: Galaxy z fold 3
 - OS: anrdoid 12
 - Browser chrome
 - Version 107

**Comment by tdn352001** [comment] 2024-02-27 08:28
Same issues

**Comment by rolandjitsu** [comment] 2024-10-04 20:20
I believe this is due to the use of the file access API. It should be disabled by default in the latest versions, so the issue should go away?

If you check the error you get in the err callback, you'll probably see something about secure context. Likely, the IP is not in a secure context (https).

**Comment by rolandjitsu** [comment] 2024-11-03 13:27
Closing this for now as it's expected behaviour.

**Closed by rolandjitsu** 2024-11-03 13:27 UTC
Labels: bug
