### ISSUE TITLE
'open' does not work in useDropZone Hook with material-ui when noClick: true

### ISSUE THREAD

**Issue by saisiddulugari-dt** [react-dropzone/react-dropzone#868] opened 2019-08-29 00:01 UTC
**Do you want to request a *feature* or report a *bug*?**

- [X ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
'open' does not work in useDropZone Hook with material-ui when noClick: true

1. My upload component is called in another component both using Mui 
1. Open function does not trigger upload box, when used with noClick: true
1. When noClick: false, it opens twice

**What is the expected behavior?**
1. It opens the upload box.

I am using version 10.1.5. This functionality used to work earlier, not sure what broke it. There has been no change in the component. 

working state: 
https://media.giphy.com/media/VgfvwIBBc6ykI0JF05/giphy.gif

**Comment by rolandjitsu** [comment] 2019-08-29 03:01
Duplicate of https://github.com/react-dropzone/react-dropzone/issues/853

**Closed by rolandjitsu** 2019-08-29 03:01 UTC
