### ISSUE TITLE
Drag and Drop doesn't work

### ISSUE THREAD

**Issue by ThomasPnt** [react-dropzone/react-dropzone#649] opened 2018-08-24 09:03 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Just installing react-dropzone 

**What is the expected behavior?**

When I try to drag and drop some files, my class on hover and accepted is triggered and active but I can't drop my file in dropzone. I must drag and drop my files somewhere in my window (out of my dropzone) and then retry and after I can drag and drop on dropzone.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Google Chrome and React-dropzone 5.0.1

**Comment by rkmarks** [comment] 2018-08-24 17:28
@ThomasPnt I was not able to duplicate this issue using the basic dropzone on the test ones at https://react-dropzone.js.org/. Are you using custom code asscoiated? if so can you attach a snippet of the code or repo where I could take a look?

**Comment by rNiall** [comment] 2018-09-28 13:58
For me, the same behavior as @henkiejan mentioned. Tested on Chrome Version 68.0.3440.75 (Official Build) (32-bit) & Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by tymochko** [comment] 2018-10-18 12:12
I also experience lack of drag-n-drop on newer versions. Current working version is 5.1.1.

By the way, some of earlier 6.x.x versions have drag-n-drop but active color is not visible.

**Comment by rolandjitsu** [comment] 2018-10-18 12:18
Without a reproducible example it is hard to tell what you're experiencing. It would be nice if one of you could make a codepen or something which illustrates the issue (using the latest version).

**Comment by lsadam0** [comment] 2018-10-19 15:56
For those experiencing this bug: Are you also using the react-dnd library?  The presence of `HTML5Backend` from react-dnd-html5-backend breaks react-dropzone, the `onDrop` event never fires

**Comment by rolandjitsu** [comment] 2018-10-20 08:56
@lsadam0 I think react-dnd can also handle file drag and drop, is there a reason why you use both libs?

In any case, it is difficult to tell what is the cause of the issue, or if there is one, if there's no example illustrating the described behaviour.

**Comment by lsadam0** [comment] 2018-10-22 14:36
@rolandjitsu Yep, react-dnd can also handle file drop.  There's no good reason we need to use both libs, it was just a decision made prior to my time on the project and I was trying to avoid re-writing that portion at the moment.  

I understand, I can't provide an example. I did debug for a bit but did not spend enough time to find the resolution.  Honestly, I would have spent less time if I had just taken the plunge and relied solely on react-dnd :) .  Thanks!

**Comment by rolandjitsu** [comment] 2018-10-23 07:13
@lsadam0 ok, well thanks for taking the time to try.

In any case, I'm closing this issue since the behaviour cannot be reproduced. If anyone can provide an example, please feel free to reopen.

**Closed by rolandjitsu** 2018-10-23 07:13 UTC

**Comment by rNiall** [comment] 2018-11-09 11:38
Step to reproduce drag and drop lack.
1. Open https://react-dropzone.netlify.com/
2. Use any of examples.
3. Left-mouse click on dropzone to open file explorer from browser.
4. Try to drag-n-drop file from opened explorer.

**Comment by rolandjitsu** [comment] 2018-11-09 11:56
@rNiall you do not drop files from the explorer that was opened in the browser window. You can either drop a file from a separate file explorer window or click and select.

**Comment by rolandjitsu** [comment] 2018-11-09 12:03
@rNiall that's intentional, see https://github.com/react-dropzone/react-dropzone/pull/551.

**Comment by rNiall** [comment] 2018-11-09 12:05
@rolandjitsu Thanks for explanation. Now I see

**Comment by ramya10** [comment] 2019-07-08 19:59
Drag and drop is not working with react-dropzone: 10.1.5, react: 16.8.x. is there any known issue with versions.

**Comment by atkimi** [comment] 2021-05-13 12:39
I had some issues with dropping files on both Firefox and Chrome running on Fedora 34. I was dragging from "Files" v40.1 in icon view. Turns out that in list view with tiny icons d&d works fine
