### ISSUE TITLE
[BUG] useFsAccessApi being true prevents directory selecting in Chrome

### ISSUE THREAD

**Issue by dwilt** [react-dropzone/react-dropzone#1245] opened 2022-10-19 17:10 UTC
**Describe the bug**
When [this commit](https://github.com/react-dropzone/react-dropzone/commit/a0342520c1192698abaf670f5ad927d15e693610#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L67) got merged, this broke Chrome being able to select folders when using the `open` method.

**To Reproduce**
Codesandbox Link: https://codesandbox.io/s/serverless-sea-isstgt

1. Open up the preview in a new window in the Codesanbox link above
2. Click the "Upload a folder" button to trigger the `open` method to select a folder
3. Notice you can't select a folder
4. Add `useFsAccessApi: false` and go through steps 1-2 but notice you can now select a folder

Screenshots showing difference:

| `useFsAccessApi: true`                                                                                                         | `useFsAccessApi: false`                                                                                                          |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/1065539/196757490-1538c77b-421f-4129-81d9-f1cb13b004da.png) | ![image](https://user-images.githubusercontent.com/1065539/196757602-db3383c4-0611-4ce9-a90a-58f614ee81c9.png) |

Something really interesting to note. When using the _inline_ browser in codesandbox with `useFsAccessApi: true`, it actually works:

![image](https://user-images.githubusercontent.com/1065539/196758030-c03794de-c3c8-4852-976d-d30666331205.png)

**Expected behavior**
When using the `open` method from `useDropzone`, you would still be able to select a folder when you have `webkitdirectory=""` on the `<input />`

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by mariush2** [comment] 2022-11-03 14:11
I have this exact issue in our current project, would be nice to see a fix for this, possibly with [window.showDirectoryPicker](https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker) or something? 🤔

**Comment by alexjball** [comment] 2022-11-07 22:58
Is there a reason you can't set useFsAccessApi to false in your usage? The referenced commit changes the default to use the API. And when you programmatically open the picker, it currently [always uses showOpenFilePicker](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L772). Supporting directory picking with the fs api would require checking for `webkitdirectory` on the input node and calling `showOpenDirectoryPicker` instead. But I'm not sure what benefit the fs API is providing over `webkitdirectory`

**Comment by mariush2** [comment] 2022-11-08 07:45
The only difference I could see is that when opening without using the fs API the user gets a browser confirmation dialog in addition to the directory picker (I might be wrong here since I didn't get it to work without setting useFsAccessApi to false).

Here's an example of the dialog in question (in norwegian):
![image](https://user-images.githubusercontent.com/24507952/200504077-a2cf432c-0edc-4b52-bda1-538b870a1650.png)

**Comment by rolandjitsu** [comment] 2024-10-03 20:27
@dwilt note that the use of file access API needs to be in a secure context (https). So the fact that it works in codesandbox it's probably due to that (likely it's not a secure context and it falls back to using the input).

@mariush2 that is a good idea, but I think that the 2 APIs allow either selection of directories or files, but not both (I cannot recall, it's been some time since I worked on that).

Btw, the use file access API has been set to false by default.

**Comment by rolandjitsu** [comment] 2024-11-04 11:39
I can confirm that https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker would only allow selecting directories and not files. So the 2 APIs are mutually exclusive in behaviour (either select files or directories).

On the other hand, the behaviour you get with an input allows to select both files and/or directories.

I was thinking that this issue could be marked as an enhancement, but I don't see how we'd be able to support a similar behaviour to the input while using the 2 existing file system access APIs.

So for now, this is just a limitation of using `{useFsAccessApi}`. I will make a note in the docs about it (making a PR now), but otherwise I'll close this issue.

**Closed by rolandjitsu** 2024-11-04 11:39 UTC
Labels: bug, needs investigation
