### ISSUE TITLE
[BUG] Finder dialog doesn't show on macOS 13 Ventura beta

### ISSUE THREAD

**Issue by mcmxcdev** [react-dropzone/react-dropzone#1222] opened 2022-08-02 10:02 UTC
**Describe the bug**
Unfortunately, I can't give much information on this since it didn't happen to me but the project manager of a client project I am working on. I thought it would be a good idea to already put this report out there anyways to be able to fix this before macOS 13 is officially released.

It seems the finder dialog doesn't open when clicking on a dropzone, but with drag and drop it does work just fine.

**Expected behavior**
Finder dialog opens and it's possible to select files to upload.

**Desktop (please complete the following information):**
 - OS: macOS 13 Ventura Beta
 - Browser: Chrome

**Comment by leerobert** [comment] 2022-08-08 00:13
To add some context, firefox works fine but Chrome does not.

**Comment by hailwood** [comment] 2022-08-11 00:26
This is also happening on Ubuntu 22.04.1 Chrome 104.0.5112.79 which is officially released

**Comment by AuthorProxy** [comment] 2022-08-26 14:57
Setting useFsAccessApi to false fix it, admins can you make this is default behaviour for samples on site? Because now they don't work at chrome

**Comment by coltoneshaw** [comment] 2022-08-27 02:01
I have a similar problem. It seems that drag and drop works fine, selecting the file does not. The issue is that the file object seems to not contain a path when selected, but when you drag and drop it does.

**Comment by coltoneshaw** [comment] 2022-08-30 01:12
This issue happens on Windows 11 as well. Just tested with Electron 18 / Windows 11 / Node 16.17

**Comment by paustint** [comment] 2022-09-02 18:02
I am having the same issue on Macos 12.5 and Chrome.

**Comment by dlech** [comment] 2022-09-03 22:03
This sounds like a duplicate of #1127.

**Closed** 2022-10-12 13:30 UTC
Labels: bug
