### ISSUE TITLE
Click events not working on the dropzone

### ISSUE THREAD

**Issue by aidenBarrett96** [react-dropzone/react-dropzone#1127] opened 2022-02-04 11:25 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Clicking on the dropzone target is not triggering the file picker to open. This is happening on our local build, production and also it looks like on the React Dropzone Docs examples: [see here](https://react-dropzone.js.org/#section-basic-example)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Click on any example of the dropzone that doesn't disable click events

**What is the expected behavior?**
Clicking the target should open the native file picker

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Currently not working on the latest Chrome on Mac

**Comment by rolandjitsu** [comment] 2022-02-05 03:51
I'm on Chrome 97 on macOS Big Sur and it seems to be ok:

https://user-images.githubusercontent.com/1479737/152627689-30631ed1-7e6b-4d6d-b5c8-44ea276ba646.mov

So what's `latest` Chrome for you?

Note that there's an update that's using the new [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API). Check and see if that works.

**Comment by OitaGG** [comment] 2022-02-08 09:17
> I'm on Chrome 97 on macOS Big Sur and it seems to be ok:
> 
>  Screen.Recording.2022-02-05.at.11.48.32.mov 
> So what's `latest` Chrome for you?
> 
> Note that there's an update that's using the new [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API). Check and see if that works.

Also not working for me. Chrome Version 98.0.4758.80 (also not working in Safari), macos Monterey.

**Comment by joshuablokland** [comment] 2022-02-08 09:19
I have the same issue, when calling `open()`.
Only in Chrome it does not open (I'm also on version 97).
I was able to upload files by just dropping them in, but the native file picker does not open.

**Comment by MaximeConan** [comment] 2022-02-08 09:23
I have the same issue as @joshuablokland  :)

**Comment by OitaGG** [comment] 2022-02-08 09:31
Just a few minutes ago it didn't work. However, now everything works correctly. I have a download area with <div {...getRootProps}> and <input {...getInputProps} />

**Comment by rolandjitsu** [comment] 2022-02-08 09:49
@OitaGG @joshuablokland @MaximeConan I'm pretty sure this is an unrelated issue to what @aidenBarrett96 is probably reporting.

It may be related to the addition of [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API).

Could you guys open a new issue and please report as much as possible as from what you're describing, I cannot reproduce the behaviour.

https://user-images.githubusercontent.com/1479737/152959980-69db7490-6158-462d-8bd6-fad412ba3454.mov

Recorded on:
* macOS 11.6.2 (Big Sur)
* Chrome 98.0
* [react-dropzone.js.org](https://react-dropzone.js.org/#section-basic-example)

Though, what I can note is that:

> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility).

Which means, it's likely that from an [\<iframe\>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe), it won't work. Which also means we will probably need to use [feature detection](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#feature_detection) to actually use the API 🤦 .

**Comment by joshuablokland** [comment] 2022-02-08 09:49
Seems to be an issue with Chrome 97 then. 
I've updated to the latest version of Chrome, and the native file picker opened.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/2347242/152961808-898f6229-4901-482e-a4b3-d626752efa9b.png">

**Comment by rolandjitsu** [comment] 2022-02-08 11:52
@OitaGG @joshuablokland @MaximeConan just a quick question: are any of you using non-secure contexts (HTTP instead of HTTPS, iframes with insecure content, etc)?

I've tested the codesandbox example and there it doesn't work because it's loading cross-origin resources, so it's insecure.

**Comment by MaximeConan** [comment] 2022-02-08 14:17
Personnally no!

**Comment by berickson1** [comment] 2022-02-08 21:46
We hit this when the react-dropzone was inside an iframe on different domains.  Parent (https://a.example.com) iFrame (https://b.example.com)

**Comment by licg9999** [comment] 2022-02-09 06:05
Would wonder, will we have a plan to fix the problem for Chrome 97 on Mac? 🙂

**Comment by joshuablokland** [comment] 2022-02-09 12:14
@rolandjitsu We do have some iframes in the application, but everything is https

**Comment by rolandjitsu** [comment] 2022-02-09 12:44
@MaximeConan then I'll probably need more context to know what's going on there.

@berickson1 ah yes. So that would definitely not work. It's the same exact issue that codesandbox has. The FS access API won't work (it throws when invoking - gonna add a `onError` cb to report errors like these).

@joshuablokland maybe you can try the following and let me know what you get:
```js
getFile()

async function getFile() {
  // open file picker
  try {
    const [fileHandle] = await window.showOpenFilePicker();
    const canRead = verifyPermission(fileHandle);

    if (canRead) {
      const fileData = await fileHandle.getFile();
      console.log(fileData);
    } else {
      console.warn('no permissions to read file')
    }
  } catch (e) {
    console.error(e)
  }
}

async function verifyPermission(fileHandle, withWrite) {
  const opts = {};
  // Check if we already have permission, if so, return true.
  if (await fileHandle.queryPermission(opts) === 'granted') {
    return true;
  }

  // Request permission to the file, if the user grants permission, return true.
  if (await fileHandle.requestPermission(opts) === 'granted') {
    return true;
  }

  // The user did not grant permission, return false.
  return false;
}
```

**Comment by rolandjitsu** [comment] 2022-02-09 12:45
> Would wonder, will we have a plan to fix the problem for Chrome 97 on Mac? 🙂

Yes. There's https://github.com/react-dropzone/react-dropzone/pull/1140 which will not enable this feature unless in a secure context. It will fallback to using an input.

**Comment by rolandjitsu** [comment] 2022-02-09 13:15
It turns out that even if in a secure context, triggering the file picker open from a different origin is not allowed (at least not in Chrome). So gonna see if either:
1. do not use FS access API by default; let the user enable it
2. there's a security error thrown when trying to trigger it so we could fallback to input click in that case and show some warning

**Comment by licg9999** [comment] 2022-02-10 02:07
Thanks @rolandjitsu , I would have a try with `@12.0.2` and give an update back if met any other issues.

**Comment by zhengheng7913** [comment] 2022-02-10 05:18
@licg9999 hi, i have same issue in chorme 97,  after install 12.0.2 and rebuild the project, the dropzone can be droped but the click func not work.
![image](https://user-images.githubusercontent.com/39586541/153342295-24787f1a-175c-47a4-ae66-c829af31ac72.png)

**Comment by zhengheng7913** [comment] 2022-02-10 13:29
> @licg9999 hi, i have same issue in chorme 97, after install 12.0.2 and rebuild the project, the dropzone can be droped but the click func not work. ![image](https://user-images.githubusercontent.com/39586541/153342295-24787f1a-175c-47a4-ae66-c829af31ac72.png)

after update chorme to a newer version of chorme 97, everythine work fine,

**Comment by joshkel** [comment] 2022-02-11 15:49
In case it helps anyone: I ran into problems with click events not working in Chrome 98 on the Mac.

It seemed to be a bug within Chrome, because manually invoking the File System API from Chrome DevTools console (without react-dropzone involved at all) resulted in a pending promise that never resolved:

```js
window.showOpenFilePicker().then(console.log).catch(console.error)
```

Restarting Chrome fixed it.

**Comment by rolandjitsu** [comment] 2022-02-12 13:08
@pahan35 @joshkel @zhengheng7913 thanks for the update. It's possible that Chrome may have had a bug. Also note that the FS access API is still an experimental technology, so you can expect issues or changes to it.

I'm still working on https://github.com/react-dropzone/react-dropzone/pull/1142 to address the issue of opening the file picker from an iframe that uses cross-origin resources.

**Comment by rolandjitsu** [comment] 2022-02-13 03:00
@berickson1 @joshuablokland just released https://github.com/react-dropzone/react-dropzone/pull/1142, could you guys try it out and let me know if the file picker opens now (you'll need the input as we fallback to it)?

**Comment by jaffemd** [comment] 2022-02-17 15:51
Hi! I just ran into the same issue and I think I finally isolated what's causing it. It is only happening on Safari for me, Chrome and Firefox function as expected.
Versions: 
`react-dropzone`: `12.0.2`
Safari: `Version 15.3 (16612.4.9.1.7, 16612)`
macOS Big Sur 11.6

The issue seems to be when trying to assign a custom input id for the file input. With this code below, I'm only seeing the `onDrop` get called around 30% of the time:
```
import React from 'react';
import { useDropzone } from 'react-dropzone';

export function Uploader() {
  const { getRootProps, getInputProps } = useDropzone({
    onDrop: (acceptedFiles) => console.log('acceptedFiles', acceptedFiles),
  });

  return (
    <div
      {...getRootProps()}
    >
      <label htmlFor="input-id">
        Input Label
      </label>
      <input {...getInputProps({ id: 'input-id' })} />
    </div>
  );
}
```

With this code below, it gets called 100% of the time:
```
import React from 'react';
import { useDropzone } from 'react-dropzone';

export function Uploader() {
  const { getRootProps, getInputProps } = useDropzone({
    onDrop: (acceptedFiles) => console.log('acceptedFiles', acceptedFiles),
  });

  return (
    <div
      {...getRootProps()}
    >
      <label htmlFor="input-id">
        Input Label
      </label>
      <input {...getInputProps()} />
    </div>
  );
}
```

Is there a better way to be able to assign a custom id to the file input? I haven't seen anything related to this in the docs. Thanks!

**Comment by jaredthecoder** [comment] 2022-03-02 06:12
@rolandjitsu Chiming in here, I noticed the same behavior with version 97 of Chrome on MacOS 12.2. So the first thing I did was update my Chrome, relaunch, and force refresh the app. Chrome was now at Chrome 99 (same OS version) and it still did not work. So then I updated to the latest version of react-dropzone (12.0.4) based on the note in #1142 that it was included by that point, and sadly it still did not work.

I can confirm that Safari on the same OS works (Version 15.3 (17612.4.9.1.5)) with react-dropzone 12.04 for clicking to select a file.

**Comment by rolandjitsu** [comment] 2022-03-06 09:37
@jaredthecoder thanks. I'm not sure if it helps 😆  So Chrome 99 on macOS 12.2 w/ react-dropzone v12.0.4 doesn't work, but Safari 15.3 works?

**Comment by dragonfire1119** [comment] 2022-04-27 19:34
I'm assuming there isn't a solution to this problem. I don't use any iframes.

**Comment by rolandjitsu** [comment] 2022-05-01 13:56
> I'm assuming there isn't a solution to this problem. I don't use any iframes.

You're gonna need to provide more info. It may be related to a specific browser/OS version.

**Comment by rolandjitsu** [comment] 2022-05-01 13:56
For the rest of the ppl experiencing this issue, it would help to upgrade to v14 and add the `onError` cb to see if there's any errors logged.

**Comment by zdila** [comment] 2022-05-02 07:18
I can confirm this issue after upgrading react-dropzone from v13 to v14. Also `onError` is missing in `typings/react-dropzone.d.ts`.

**Comment by rolandjitsu** [comment] 2022-05-03 03:32
> I can confirm this issue after upgrading react-dropzone from v13 to v14. ...
> 
> (Tested on latest Vivaldi on Linux, no iframes involved, https domain)

@zdila what is the issue that you're experiencing? I'm not familiar with that browser. Does it happen in other browsers on Linux?

> Also onError is missing in typings/react-dropzone.d.ts.

Just pushed a fix (https://github.com/react-dropzone/react-dropzone/pull/1185).

**Comment by Alexsandr** [comment] 2022-05-06 08:03
I got the same problem after adding `accept` option. 
For example: `accept: { "image/*": [] }` 
I use Сhrome on Linux, I have not tested it in others. Perhaps the problem is in the use of this option. 
I hope this information helps.

**Comment by mohd-akram** [comment] 2022-07-06 07:49
I have the same problem as @Alexsandr. The fix for it seems to be passing `useFsAccessApi={false}`.

**Comment by dlech** [comment] 2022-09-03 19:53
This issue is reproducible at https://react-dropzone.js.org/#section-accepting-specific-file-types. It works in Firefox 103, but not in Chromium 105 (on Linux).

Adding a `console.error` to `onError` doesn't log anything.

**Comment by dlech** [comment] 2022-09-03 20:19
Debugging local build (not secure context) shows that the fallback doesn't work because it tries to "click" the input element from a `catch` callback which is not considered user-initiated and therefore ignored.

![image](https://user-images.githubusercontent.com/963645/188286487-779b0cc9-1f8f-439a-aef6-58d11a2e124e.png)

**Comment by dlech** [comment] 2022-09-03 20:38
Here is the full `DOMException`. We are getting a security error, not because we aren't in a secure context, but rather because the call to `window.showOpenFilePicker()` is not called in a user event handler.

```
{
    "stack": "Error: Failed to execute 'showOpenFilePicker' on 'Window': Must be handling a user gesture to show a file picker.\n    at eval (webpack://react-dropzone/./src/index.js?:767:14)\n    at eval (webpack://react-dropzone/./src/index.js?:842:7)\n    at eval (webpack://react-dropzone/./src/utils/index.js?:221:12)\n    at Array.some (<anonymous>)\n    at eval (webpack://react-dropzone/./src/utils/index.js?:219:16)\n    at HTMLUnknownElement.callCallback (webpack://react-dropzone/./node_modules/react-dom/cjs/react-dom.development.js?:4161:14)\n    at Object.invokeGuardedCallbackDev (webpack://react-dropzone/./node_modules/react-dom/cjs/react-dom.development.js?:4210:16)\n    at invokeGuardedCallback (webpack://react-dropzone/./node_modules/react-dom/cjs/react-dom.development.js?:4274:31)\n    at invokeGuardedCallbackAndCatchFirstError (webpack://react-dropzone/./node_modules/react-dom/cjs/react-dom.development.js?:4288:25)\n    at executeDispatch (webpack://react-dropzone/./node_modules/react-dom/cjs/react-dom.development.js?:9038:3)"
}
```

So, perhaps the problem is with the way `composeEventHandlers` uses `Array.some`?

**Comment by dlech** [comment] 2022-09-03 20:46
I think the exceptions above were caused by being paused in the debugger and should be ignored. I changed the breakpoints and now I am getting a user abort error even though the dialog is never shown:

![image](https://user-images.githubusercontent.com/963645/188287177-297bea4d-89ca-4bcd-9218-525011b67784.png)

**Comment by dlech** [comment] 2022-09-03 21:33
After more experimenting, it seems that the issues is triggered by a lack of a `description` key in the `types` array in the `FilePickerOptions`. So, this is probably a Chromium bug (I filed https://crbug.com/1359728). However, it would still be useful to allow passing additional options to the file system API.

**Comment by yash14022001** [comment] 2022-09-26 05:52
I am having this same issue on both firefox(105.0.1 (64-bit) & chrome (105.0.5195.102 (Official Build) (64-bit)) with ubuntu 22.04
click is only working after removing the accept parameters
I tried using `useFsAccessApi: false` settings but didn't work
But what I am curious about is that when I make the field from `display: none` to `display: block` or anything like that, then file picker opens with correct file types

**Comment by swoppy** [comment] 2022-10-12 08:33
Seems like this works now on chrome version 106.0.5249.119, with no workarounds applied

**Closed** 2022-10-12 13:30 UTC
Labels: needs investigation, needs example

**Comment by Cafezinho** [comment] 2023-02-09 23:33
I am using React inside iframe from different origin, and clicking a file still resuts in fakepath being added instead of file. Can someone help?

**Comment by kiikka** [comment] 2024-04-08 10:32
Im getting this error with MAC and Chrome Version 123.0.6312.107 (Official Build) (arm64).

Works fine with Safari and Firefox. It also works when ran locally

`TypeError: Failed to execute 'showOpenFilePicker' on 'Window': Invalid type: application/pdf,application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text,application/vnd.oasis.opendocument.spreadsheet,text/plain`

**Comment by sebas0126** [comment] 2024-04-19 23:00
> Im getting this error with MAC and Chrome Version 123.0.6312.107 (Official Build) (arm64).
> 
> Works fine with Safari and Firefox. It also works when ran locally
> 
> `TypeError: Failed to execute 'showOpenFilePicker' on 'Window': Invalid type: application/pdf,application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text,application/vnd.oasis.opendocument.spreadsheet,text/plain`

Same problem here

**Comment by sebipap** [comment] 2024-06-07 00:02
> I also had this problem. Everything worked fine in Safari, while there was a problem with Chrome.
> 
> I decided to restart my MacBook, and the problem disappeared.
> 
> I can't say what the version of Chrome was before, but the current one is `Version 98.0.4758.80 (Official Build) (x86_64)`.

same here!
