### ISSUE TITLE
Video upload doesn't work on iphone and ipad

### ISSUE THREAD

**Issue by udayan46** [react-dropzone/react-dropzone#1237] opened 2022-09-09 05:23 UTC
Hello everyone facing this problem from long, any luck on this, working fine for all but seems like iphone and ipad is not accepting the video file 

 <div className="dropzonecover dropzonenew" key={`drop`}>
                                <div className="img_wrpcover relative">
                                  {/* <img className="dropimgcover" /> */}
                                  {isEmpty(fileUrl) ? ("") : (
                                    <video
                                      controls
                                      controlsList="nodownload"
                                      className="dropimgcover"
                                       playsinline
                                    >
                                      <source
                                        src={coverimage}
                                        type="video/mp4"
                                      />
                                    </video>
                                  )}
                                </div>
                                <Dropzone
                                  onDrop={(e) => this.onDropFiles(e)}
                                  accept="video/mp4"
                                  multiple={false}
                                  noDragEventsBubbling={true}
                                >
                                  {({ getRootProps, getInputProps }) => (
                                    <div
                                      {...getRootProps()}
                                      className="h-full w-full absolute top-0"
                                    >
                                      <input {...getInputProps()} />
                                      <p className="paragraph-seconday text-xs pt-10">
                                        {LocaleStrings.imageupload}
                                      </p>
                                    </div>
                                  )}
                                </Dropzone>
                              </div>
                              
                              // onDropFiles function
                                onDropFiles = async (files) => {
                                    // console.log('ondrop',files)
                                    let file = files[0];
                                    let filearr = [];
                                    const reader = new FileReader();
                                    reader.readAsArrayBuffer(file);
                                    
                                    reader.onload = (e) => {
                                      file.url = e.target.result;
                                      filearr.push(file);
                                    };
                                   
                                    this.setState({ fileArrNew: filearr });
                                    this.setState({ fileUrl: URL.createObjectURL(file) });
                                    let dataduration = await  this.validateUploadedFile(file);
                                    // console.log('dataduration',dataduration)
                                    this.setState({ videoDuration: dataduration });
                                  };

**Comment by m-a-h1** [comment] 2023-06-11 10:32
facing the same issue, it is working fine on all other devices but on iphone , when i select the video, page get refreshed.
if anyone know the issue please let us know

**Comment by rolandjitsu** [comment] 2024-10-03 20:22
@udayan46 some way to reproduce the issue is needed.

@m-a-h1 your issue may be different. Could you provide some way to reproduce the issue, a codesandbox or something.

**Comment by rolandjitsu** [comment] 2024-11-02 14:39
Closing this for now. If it's still an issue, please provide a codesandbox that illustrates the issue.

**Closed by rolandjitsu** 2024-11-02 14:39 UTC
Labels: bug, needs example
