### ISSUE TITLE
[BUG] File picker not showing on Chrome/Edge when extension with underscore exists

### ISSUE THREAD

**Issue by AlexSchoenfeld** [react-dropzone/react-dropzone#1257] opened 2022-12-06 08:57 UTC
**Describe the bug**
In Google Chrome and Microsoft Edge it's currently not possible to show the file picker if accept has any file extension containing an underscore (e.g. '.zip_1'). It still works in Mozilla Firefox.

It's showing **TypeError: Failed to execute 'showOpenFilePicker' on 'Window': Extension '.zip_1' contains invalid characters.** in the console output if I click on the dropzone.

**To Reproduce**
Here is a small code sample:

```
import {useDropzone} from 'react-dropzone'

export default function Home() {

  const { getRootProps, getInputProps } = useDropzone({
    accept: { 'application/zip': ['.zip', '.zip_1'] }
  })

  return (
    <>
      <div {...getRootProps()} id="upload-file" style={{width: '200px', height: '200px'}}>
        <input {...getInputProps()} />
      </div>
    </>
  )
}
```

**Expected behavior**
Should show the file picker dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/12166347/205865325-07c0dbdb-edf3-4a86-9fb4-ff03df90b696.png)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome; Edge
 - Version 108.0.5359.95 (Official Build) (64-bit); 107.0.1418.56 (Official build) (64-bit)

**Comment by joebochill** [comment] 2023-02-24 16:27
We're having the exact same issue. We did find a temporary workaround...if you don't specify the MIME type, it seems to work fine:

**Comment by bensewell** [comment] 2023-03-02 10:36
@joebochill - does it still show that option in the file picker? For me it filters that option out, and warns in the console.

**Comment by bensewell** [comment] 2023-03-02 10:45
I've raised this bug on Chromium:

https://bugs.chromium.org/p/chromium/issues/detail?id=1420912

**Comment by joebochill** [comment] 2023-03-02 22:00
@bensewell yes, I do get a warning in the console, but I am able to select the file from the picker window (in Chrome, that's all I checked).

On a mac, the file picker window defaults to "JPEG Images", so I have to toggle the dropdown to allow "All Files", but then I am able to select the files with the underscore in the extension:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/29152776/222568289-6940c017-e468-4243-80c1-631055853abe.png">

**Comment by bsmedberg-xometry** [comment] 2023-12-18 17:08
I apologize in advance for commenting in an old ticket, but does anyone know under what circumstances this bug appears? We're trying to work around it, but cannot reproduce it locally and it's clearly not 100% of users... our testing shows only a relatively small % of users seeing this issue (we also have users uploading CAD files in x_t and x_b format).

**Comment by rolandjitsu** [comment] 2024-10-04 20:26
Disabling the file access API should make this go away. We've also made this option disabled by default in the latest version.

**Comment by rolandjitsu** [comment] 2024-11-03 13:26
Closing this for now. If the issue persists we can reopen and revisit the issue. 

Also, since browsers do not agree with underscores in file extensions when passing to https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker, it would be my recommendation to avoid doing that.

**Closed by rolandjitsu** 2024-11-03 13:26 UTC
Labels: bug

**Comment by ericman314** [comment] 2025-01-14 17:41
I used to have problems with `x_t` files, but the latest version works perfectly. Thank you! 

However, it is still broken with `useFsAccessApi={true}`. But without that property, it works perfectly.

react-dropzone version: 14.3.5
Chrome version: 131
OS: Pop!_OS 22.04 LTS
