### ISSUE TITLE
onDrop method not being called after selecting a file.

### ISSUE THREAD

**Issue by ckorhonen** [react-dropzone/react-dropzone#1097] opened 2021-09-24 17:58 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

When I click the dropzone, the file dialog opens. I select a file either by double clicking or clicking the upload button on the dialog. The dialog dismisses. 

About 80% of the time, nothing happens. The `onDrop` method is not called. The remaining 20% of the time, it works as normal.

File is a valid filetype/size and I see no errors on my console.

If I drag and drop a file from Finder, it consistently works as expected - I've only encountered this when selecting from a dialog.

**What is the expected behavior?**

`handleDrop` gets called consistently and I'm able to upload my file.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
* My implementation seemingly mirrors the documentation, and I'm using the latest version.
* My browser is Safari 15, public release version, and I've reproduced this using both Big Sur and the Monterrey beta. 
* I have not encountered this issue with other versions of Safari.

**Comment by rolandjitsu** [comment] 2021-09-27 02:37
@ckorhonen where is the `handleDrop` prop documented? Because there's no such prop exported from this lib.

**Comment by ckorhonen** [comment] 2021-09-27 10:26
> @ckorhonen where is the `handleDrop` prop documented? Because there's no such prop exported from this lib.

Sorry, my mistake - I meant to type onDrop

**Comment by rolandjitsu** [comment] 2021-09-28 22:51
@ckorhonen ok, got it. I've just tried the basic example from our documentation in `Safari 14.1.2 (16611.3.10.1.6)` on `macOS Big Sur 11.5.2` and the `{onDrop}` cb is triggered on every select. I haven't tried v15, but I'll try it once I update.

Would you mind sharing how you're using the dropzone? Are you experiencing this when using our docs?

**Comment by Newpoki** [comment] 2022-01-19 13:13
I've experimented the same issue, but when trying to upload twice in a row the same file.

I upload it a first time, it works, the `onDrop` callback is called.
If i upload the same file a second time, it's not triggered, but if it's a different file, it will work

**Comment by rolandjitsu** [comment] 2022-01-30 01:15
@ckorhonen @Newpoki I've actually tried to reproduce in Safari and I still cannot get the same behaviour you describe.


https://user-images.githubusercontent.com/1479737/151683029-d9fe3a75-c3b5-44c0-903d-69d4d1dbdb1e.mp4

**Comment by meetdheeraj** [comment] 2022-02-02 05:10
For me, this isn't working even for the first time. I'm using React 17+
`import Dropzone, { useDropzone } from 'react-dropzone';
...

<Dropzone
              onDrop={(acceptedFiles, fileRejections, event) =>
                console.log('***************', acceptedFiles, fileRejections, event)
              }
              onDropRejected={lol => console.log('##########3', lol)}
            >
              {({ getRootProps, getInputProps }) => (
                <section className="container">
                  <div {...getRootProps()}>
                    <input {...getInputProps()} />

                    <div className={styles.assemblyUploadFormRow}>
                      <div className={styles.dropzoneArea}>
                        <IconButton
                          ariaLabel="file upload"
                          iconProps={{
                            iconName: FluentIconName.CloudUpload,
                          }}
                        />
                        Drag n drop some files here, or click to select files
                      </div>
                    </div>
                  </div>
                </section>
              )}
            </Dropzone>
`

Those consoles never get printed. On click, I do get file uploader but on selection, nothing happens in the console. Same for drag and drop.

**Comment by rolandjitsu** [comment] 2022-02-02 09:30
Are the examples at https://react-dropzone.js.org/ working for you?

**Comment by meetdheeraj** [comment] 2022-02-02 09:39
> Are the examples at https://react-dropzone.js.org/ working for you?

Oops, sorry. I got it working now. I was using dropzone on a modal window. After adding `noDragEventsBubbling: true` it started working. Still couldn't get it working with `<Dropzone ` syntax though but the other syntax that's used in most of the examples.

**Comment by meetdheeraj** [comment] 2022-02-02 09:42
> For me, this isn't working even for the first time. I'm using React 17+
> 
> ```
> import Dropzone, { useDropzone } from 'react-dropzone';
> ...
> <Dropzone
>               onDrop={(acceptedFiles, fileRejections, event) =>
>                 console.log('***************', acceptedFiles, fileRejections, event)
>               }
>               onDropRejected={lol => console.log('##########3', lol)}
>             >
>               {({ getRootProps, getInputProps }) => (
>                 <section className="container">
>                   <div {...getRootProps()}>
>                     <input {...getInputProps()} />
> 
>                     <div className={styles.assemblyUploadFormRow}>
>                       <div className={styles.dropzoneArea}>
>                         <IconButton
>                           ariaLabel="file upload"
>                           iconProps={{
>                             iconName: FluentIconName.CloudUpload,
>                           }}
>                         />
>                         Drag n drop some files here, or click to select files
>                       </div>
>                     </div>
>                   </div>
>                 </section>
>               )}
>             </Dropzone>
> ```
> 
> Those consoles never get printed. On click, I do get file uploader but on selection, nothing happens in the console. Same for drag and drop.

I needed dropzone inside a modal window and seems modal window introduces some issue here. Got it working with `noDragEventsBubbling: true,` as shown below ,

```
const { getRootProps, getInputProps } = useDropzone({
    onDrop,
    noDragEventsBubbling: true,
  });
...
<div {...getRootProps()}>
                <input {...getInputProps()} />
....
```

**Comment by rolandjitsu** [comment] 2022-02-02 12:00
@meetdheeraj ok. Would help if you could share a codesandbox with a similar scenario as yours so we can see if there's anything we can do.

Though, I think @ckorhonen is probably describing a different issue.

**Comment by jaffemd** [comment] 2022-02-17 15:54
Hi! I just ran into the same issue and I think I finally isolated what's causing it. It is only happening on Safari for me, Chrome and Firefox function as expected.
Versions: 
`react-dropzone`: `12.0.2`
Safari: `Version 15.3 (16612.4.9.1.7, 16612)`
macOS Big Sur 11.6

The issue seems to be when trying to assign a custom input id for the file input. With this code below, I'm only seeing the `onDrop` get called around 30% of the time:
```
import React from 'react';
import { useDropzone } from 'react-dropzone';

export function Uploader() {
  const { getRootProps, getInputProps } = useDropzone({
    onDrop: (acceptedFiles) => console.log('acceptedFiles', acceptedFiles),
  });

  return (
    <div
      {...getRootProps()}
    >
      <label htmlFor="input-id">
        Input Label
      </label>
      <input {...getInputProps({ id: 'input-id' })} />
    </div>
  );
}
```

With this code below, it gets called 100% of the time:
```
import React from 'react';
import { useDropzone } from 'react-dropzone';

export function Uploader() {
  const { getRootProps, getInputProps } = useDropzone({
    onDrop: (acceptedFiles) => console.log('acceptedFiles', acceptedFiles),
  });

  return (
    <div
      {...getRootProps()}
    >
      <label htmlFor="input-id">
        Input Label
      </label>
      <input {...getInputProps()} />
    </div>
  );
}
```

Is there a better way to be able to assign a custom id to the file input? I haven't seen anything related to this in the docs. Thanks!

**Comment by rolandjitsu** [comment] 2022-03-06 09:33
@jaffemd I know that using `label` with root props triggers 2 clicks. But what you're describing doesn't make a lot of sense (using an ID on the input shouldn't change much, unless the click is triggered from the `label` which may have an issue). I would need to test this.

**Comment by amonks** [comment] 2022-03-30 00:33
thanks, @jaffemd! you saved me some debugging time :)

safari 15.4; react-dropzone 11.0.3—The callback wasn't called consistently when using the label element. Removing that element worked for my use-case.

**Comment by cunisia** [comment] 2022-08-26 08:18
@Newpoki I had the exact same behaviour as you (`onDrop` not being called the second time when selecting the same file twice in a row), and I realised the only difference with the sample used by @rolandjitsu was that I had forgotten to wrap my input in a `div` being passed `getRootProps()` attributes. Adding this wrapper fixed the issue for me 🙂

**Comment by devth** [comment] 2022-09-27 00:25
I'm having a similar issue where `onDrop` is never called in Safari. My `input` is in a [MUI Menu](https://mui.com/material-ui/react-menu/). If I render it outside the menu it works. The suggested fixes above (remove `id`,  moving the `label`, `noDragEventsBubbling: true`) don't fix it.

**Comment by SavePointSam** [comment] 2022-11-23 15:19
Had the same issue as above, picking the same file a second time yielded no change. I switched my wrapper from a `<label />` to a `<div />` and removed `onClick: false`, then the file was loading in the second time as expected.

**Comment by fatihpolatli** [comment] 2022-12-05 00:23
hi, same for me. if you select same file again, onDrop isnt triggered second time. but trigger if different file. you can see the code below @rolandjitsu 

```
import React, { useCallback, useEffect, useState } from "react"
import { useDropzone } from "react-dropzone"
import { FormattedMessage, useIntl } from "gatsby-plugin-intl-v4"
import { useFormikContext } from "formik"
import { Button, Spinner } from "@tmu/components/common"
import { v4 as uuidv4 } from "uuid"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faPlus } from "@fortawesome/pro-light-svg-icons/faPlus"
import { faTrash } from "@fortawesome/pro-solid-svg-icons/faTrash"
import { faRepeat } from "@fortawesome/pro-solid-svg-icons/faRepeat"
import {
  StyledImagesContainerList,
  StyledDropzoneContent,
  StyledImageControls,
  StyledImageThumb,
  StyledSpinner,
} from "./index.styles"
import { readFile } from "@tmu/utils/image"
import ImageCropper from "./ImageCropper"
import { useToast } from "@tmu/hooks"
import ReactTooltip from "react-tooltip"

const Dropzone = ({ onDrop, accept, isEmpty, children }) => {
  // Initializing useDropzone hooks with options
  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept,
  })
  return (
    <div {...getRootProps()} onClick={(e) => e.preventDefault()}>
      {
        <input
          id="dropzoneInput"
          className="dropzone-input"
          {...getInputProps()}
        />
      }
      <StyledDropzoneContent active={isDragActive}>
        {!isEmpty ? (
          children
        ) : isDragActive ? (
          <FormattedMessage
            id="dashboard::forms::releaseFiles"
            defaultMessage="Release to drop the files here"
            tagName="p"
          />
        ) : (
          <>
            <div
              className="open-dialog"
              onClick={() => {
                document.getElementById("dropzoneInput").click()
              }}>
              <FontAwesomeIcon icon={faPlus} size="3x" />
            </div>
            <FormattedMessage
              id="dashboard::forms::dragFiles"
              defaultMessage="Drag 'n' drop some files here, or click to select files"
              tagName="p"
            />
          </>
        )}
      </StyledDropzoneContent>
    </div>
  )
}

const Image = ({ image, loading, id, onRemove, onEdit }) => {
  const [imgSrc, setImgSrc] = useState(image)
  const isUserUpload = id.indexOf("user-upload") > -1
  const { formatMessage } = useIntl()

  useEffect(() => {
    if (!isUserUpload) {
      return
    }
    readFile(image).then((src) => {
      setImgSrc(src)
    })
    if (imgSrc === image) onEdit(id)
  }, [image, isUserUpload, imgSrc])

  return (
    <>
      <StyledImageThumb>
        <img width={196} height={118} alt={`img-${id}`} src={imgSrc} />
        <StyledImageControls>
          {loading ? (
            <StyledSpinner>
              <Spinner condensed />
            </StyledSpinner>
          ) : (
            <>
              {isUserUpload && (
                <Button
                  variant="text"
                  label="crop"
                  data-tip={formatMessage({
                    id: "dashboard::forms::replace",
                    defaultMessage: "Replace with another one",
                  })}
                  data-for="repeat"
                  onClick={(e) => {
                    e.preventDefault()
                    onEdit(id)
                  }}>
                  <ReactTooltip
                    place="left"
                    type="info"
                    textColor="black"
                    backgroundColor="white"
                    id="repeat"
                    className="tooltip"
                    delayShow={200}
                  />
                  <FontAwesomeIcon icon={faRepeat} />
                </Button>
              )}
              <Button
                variant="text"
                label="trash"
                data-tip={formatMessage({
                  id: "dashboard::forms::delete",
                  defaultMessage: "Delete",
                })}
                data-for="remove"
                onClick={(e) => {
                  e.preventDefault()
                  onRemove(id)
                }}>
                <ReactTooltip
                  place="left"
                  type="info"
                  id="remove"
                  textColor="black"
                  backgroundColor="white"
                  className="tooltip"
                  delayShow={200}
                />

                <FontAwesomeIcon icon={faTrash} />
              </Button>
            </>
          )}
        </StyledImageControls>
      </StyledImageThumb>
    </>
  )
}

const ImageList = ({ images, processing, onRemove, onEdit }) => {
  // render each image by calling Image component
  const renderImage = ({ image, id, order }) => (
    <Image
      image={image}
      key={`${id}-image`}
      id={id}
      loading={processing.indexOf(id) > -1}
      onEdit={onEdit}
      onRemove={onRemove}
    />
  )

  // Return the list of files
  return (
    <StyledImagesContainerList>
      {images?.length && images.map(renderImage)}
      <div
        className="open-dialog"
        onClick={() => {
          document.getElementById("dropzoneInput").click()
        }}>
        <FontAwesomeIcon icon={faPlus} size="3x" />
      </div>
    </StyledImagesContainerList>
  )
}

const ImageGallery = ({ onDeleteImage, processingImages }) => {
  const [croppingImage, setCroppingImage] = useState(null)
  const { error: errorToast } = useToast()

  const { values, setFieldValue } = useFormikContext()
  const handleDrop = useCallback(
    (acceptedFiles) => {
      Promise.all(
        acceptedFiles.map((file, index) => {
          const id = `user-upload-${uuidv4()}`
          return {
            id,
            image: file,
            order: index,
          }
        })
      ).then((results) =>
        setFieldValue("images", [...values.images, ...results])
      )
    },
    [values.images]
  )

  const handleRemoveImage = useCallback(
    (id) => {
      id.indexOf("user-upload") === -1
        ? onDeleteImage({
            variables: { input: { id } },
          })
            .then(({ data, errors }) => {
              if (errors?.length) {
                throw new Error(errors[0].message)
              } else if (data?.deletePartnerImage?.success) {
                setFieldValue("images", [
                  ...values.images.filter((img) => img.id !== id),
                ])
              }
            })
            .catch((err) => {
              errorToast(err?.[0]?.message || err?.message || err)
            })
        : setFieldValue("images", [
            ...values.images.filter((img) => img.id !== id),
          ])
    },
    [values.images]
  )

  return (
    <>
      <Dropzone
        onDrop={handleDrop}
        accept={"image/*"}
        isEmpty={values.images?.length === 0}>
        <ImageList
          images={values.images}
          onRemove={handleRemoveImage}
          onEdit={(id) =>
            setCroppingImage(values.images.find((image) => image.id === id))
          }
          processing={processingImages}
        />
      </Dropzone>
      <ImageCropper
        isOpen={!!croppingImage}
        image={croppingImage?.image}
        id={croppingImage?.id}
        onConfirm={({ result, id }) => {
          const newImages = values.images.map((image) =>
            image.id === id ? { ...image, image: result } : image
          )
          setFieldValue("images", newImages)
          setCroppingImage(null)
        }}
        onCancel={() => setCroppingImage(null)}
      />
    </>
  )
}

export default ImageGallery
```

**Comment by cjauvin** [comment] 2022-12-21 19:17
I seem to be having a similar issue with the same file being uploaded twice, for me using Chrome on Ubuntu. This bug only seems to affect the `input` mechanism: if I select the same file, using the file chooser, the second time nothing happens. If I try then to drag that same file in my dropzone, while in that state, it works though.

**Comment by dtpietrzak** [comment] 2023-03-03 14:47
When it fails to work, I'm getting a "onFileDialogCancel" call, even though I'm choosing "upload" and not "cancel" in the browser's native file viewer. Only if using the native file picker as well. If I drag a file, it works every time. Only an issue on Safari 16.3, not on Chrome, haven't tried Firefox...

**Comment by dtpietrzak** [comment] 2023-03-03 16:47
It's firing from the "onWindowFocus" function. files.length is 0 for some reason.

**Comment by dtpietrzak** [comment] 2023-03-03 16:56
Okay, so my issue is that the <input {...getInputProps()} /> was double nested. So maybe it MUST be the direct child of the component with {...getRootProps()}?

I is working consistently for me now.

**Comment by andrew-oko-odion** [comment] 2023-06-19 18:20
I can confirm this bug still exit with `react-dropzone version 14.2.3` on `Firefox 112.0.2 (64-bit)` on `Mac Ventra 13.4` 

it only happens when using selecting from the file dialog

I also quick tested with Chrome and it seams to work file when selecting from the file dialog

**Comment by williamisnotdefined** [comment] 2024-04-11 02:42
Guys I have to share an important info with all of you, it took me some hours.

It was a **folder permission issues**!! I was trying to upload from my "pictures" folder (Fedora latest version + Chrome). I copied the file to another folder and it worked!!!

I found it on this reply (credits are not mine):
https://github.com/react-dropzone/react-dropzone/issues/581#issuecomment-371587898

**Comment by rolandjitsu** [comment] 2024-10-03 19:34
I wonder if the original issue described here is still relevant or not. If yes, it would help to get some reproducible example so I can investigate.

**Comment by rolandjitsu** [comment] 2024-11-02 14:33
I'm gonna go ahead and close this for now. If there's further issues, please open a new issue and provide a codesandbox to make it easy to replicate.

**Closed by rolandjitsu** 2024-11-02 14:33 UTC
Labels: needs example
