### ISSUE TITLE
Browser file picker opens twice when using `open()` and `useDropZone()` 

### ISSUE THREAD

**Issue by chriswhong** [react-dropzone/react-dropzone#1108] opened 2021-12-10 16:48 UTC
I observed this when using v11.4.2 and trying to progammatically open the file picker.  It would ignore the first selection, open the picker again, and then would work as expected. 

I tried things in https://github.com/react-dropzone/react-dropzone/issues/182 to no avail.  In the end I was able to work around it by using `e.stopPropagation()` to intercept the call to `open()`

```
const handleSelectClick = (e: any) => {
    // prevents the file picker "double open" bug
    e.stopPropagation()
    open()
  }
```

**Comment by rolandjitsu** [comment] 2022-01-10 03:00
Would be great to provide a way to reproduce this as the example from https://react-dropzone.js.org/#section-opening-file-dialog-programmatically works as expected.

**Comment by rolandjitsu** [comment] 2022-01-30 01:26
@chriswhong here's an illustration of the example working as expected:


https://user-images.githubusercontent.com/1479737/151683160-950536f8-d4d1-4bdf-b4bf-5f08f3edcb4c.mov

From the docs, also note this:

> Note that for security reasons most browsers require popups and dialogs to originate from a direct user interaction (i.e. click).

> If you are calling open() asynchronously, there’s a good chance it’s going to be blocked by the browser. So if you are calling open() asynchronously, be sure there is no more than 1000ms delay between user interaction and open() call.

> Due to the lack of official docs on this (at least we haven’t found any. If you know one, feel free to open PR), there is no guarantee that the allowed delay duration will not be changed in later browser versions. Since implementations may differ between different browsers, avoid calling open asynchronously if possible.

**Comment by rolandjitsu** [comment] 2022-02-02 04:52
@chriswhong another note is that if you bind the `open` to `onClick` on some element inside the dropzone, it will definitely trigger twice because of how events are bubbling up the DOM tree. This is actually explained in https://github.com/react-dropzone/react-dropzone/pull/1123 which I'll merge soon.

To get around it, you can use `noClick` on the dropzone (`useDropzone({noClick: true})`). Or stopping event propagation from the click cb also works.

**Comment by rolandjitsu** [comment] 2022-02-05 03:37
Closed by https://github.com/react-dropzone/react-dropzone/commit/3ad4f007d70401e1d9adbc93ba2dfd69cc8c2a27. Added a caveats section where I've explained this and how to get around this issue.

**Closed by rolandjitsu** 2022-02-05 03:37 UTC
Labels: needs investigation, needs example
