### ISSUE TITLE
[BUG] Customize error message

### ISSUE THREAD

**Issue by VictorPulzz** [react-dropzone/react-dropzone#1235] opened 2022-09-06 13:25 UTC
Hello guys, how I can customize this message?
<img width="322" alt="image" src="https://user-images.githubusercontent.com/23406402/188646756-01d1db79-874f-42ee-9b14-69ff44ee6d9a.png">
Also would be cool if I got message form useDropzone, for get error immediately. Like this:
```ts
const {errors} = useDropzone({
   maxFiles: 3
}) 
```
Structure errors: 
```ts
[
   {
       type: 'invalid_format'
       message: 'Files have invalid format',
       invalidFiles: [File, File]
   }, {
       type: 'to_many_files'
       message: `You tryed add file more > ${maxFiles}`
       invalidFiles: [File, File]
   }
]
```

**Comment by rolandjitsu** [comment] 2024-10-03 20:19
Related to https://github.com/react-dropzone/react-dropzone/issues/1221 and https://github.com/react-dropzone/react-dropzone/issues/1197.


Btw, this is an enhancement, not a bug.

In any case, closing as duplicate.

**Closed by rolandjitsu** 2024-10-03 20:19 UTC
Labels: bug
