### ISSUE TITLE
When adding noClick opening the file selection programmatically does not work.

### ISSUE THREAD

**Issue by JoshaMunnik** [react-dropzone/react-dropzone#859] opened 2019-08-02 12:18 UTC
While updating a component to use the latest version (10.1.7) of DropZone I came accross the following bug.

When adding noClick it is not longer possible to open the file selection programmatically.

The reason is that the version tested adds a `disabled=""` to the input field via `getInputProps`

This behavior can be tested with the examples at https://react-dropzone.js.org/#opening-file-dialog-programmatically

Renaming the disabled attribute (via the Inspector) of the hidden file input field on that page, will make the button click work again.

**Comment by thaihoa-fe** [comment] 2019-08-05 11:11
same issue here

**Comment by nowinskp** [comment] 2019-08-05 12:14
Same issue.

**Comment by RichardDonizette** [comment] 2019-08-05 17:56
Using the {disabled: false} object inside getInputProps solves the problem.
Example:
<input {... getInputProps ({disabled: false})} />

**Comment by rolandjitsu** [comment] 2019-08-06 03:30
There's an easy fix for this, but this will have some consequences for ppl using labels that don't have `for` attr with a dropzone inside. Will fix this weekend if nobody attempts a PR.

**Comment by thaihoa-fe** [comment] 2019-08-07 10:57
> Using the {disabled: false} object inside getInputProps solves the problem.
> Example:
> <input {... getInputProps ({disabled: false})} />

this solution works

**Comment by toncic** [comment] 2019-08-11 18:19
> Using the {disabled: false} object inside getInputProps solves the problem.
> Example:
> <input {... getInputProps ({disabled: false})} />

Is there any reason to be disabled by default? I think all of us are expecting NOT to be disabled by default.

**Comment by rolandjitsu** [comment] 2019-08-13 00:38
Will close this as the issue is tracked in https://github.com/react-dropzone/react-dropzone/issues/853.

**Closed by rolandjitsu** 2019-08-13 00:38 UTC
