### ISSUE TITLE
Drag and Drop not Working on safari

### ISSUE THREAD

**Issue by Shubham-S-Yadav** [react-dropzone/react-dropzone#726] opened 2018-12-13 12:16 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Drag and Drop functionality not working on safari.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Simply drag a file and drop in the drop zone.
1.No file will be uploaded.

**What is the expected behavior?**
The file dropped in the drop zone area is expected to be uploaded but it is not. Even tried with the given examples but they too don't work for me.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
OS: macOS Sierra Version: 10.12.6 | Safari version: : 11.0| react-dropzone version: 7.0.1

**Comment by rolandjitsu** [comment] 2018-12-15 18:13
@Shubham-S-Yadav I don't have Safari 11 on hand, but I just tested on `Version 12.0.2 (12606.3.4.1.4)` on same macOS version and the dropzone works as expected as far as I can tell.

On a side note, this lib does not handle any uploads.

**Comment by Shubham-S-Yadav** [comment] 2018-12-17 05:13
@rolandjitsu Yes I've checked on latest versions too it works very well with latest safari versions but it is not working for versions before 11.1. And by upload I mean to say Drag & Drop Functionality

**Comment by rolandjitsu** [comment] 2018-12-17 08:21
@Shubham-S-Yadav true, I just tried it using saucelabs and it seems like drag 'n' drop does not work. Might take some time to investigate this issue using saucelabs.

**Comment by jordiponsllaurado** [comment] 2018-12-17 11:20
@rolandjitsu is it possible that it's also happening with Chrome? 

I'm having the same issue but using latest Chrome version on a mac.

**Comment by karensg** [comment] 2018-12-17 22:39
Same problem with Chrome. I have several uploads on the website. The only that does not work is the one in the modal of https://material-ui.com/

**Comment by jordiponsllaurado** [comment] 2018-12-18 08:08
For us it also fails in Firefox and the Dropzone is inside a modal too

**Comment by rolandjitsu** [comment] 2018-12-18 09:50
@jordiponsllaurado no, it is not possible because I have tested the latest versions of major browsers and all examples work as expected.

@karensg please open a new issue and provide a reproducible example illustrating your issue.

**Comment by jordiponsllaurado** [comment] 2018-12-18 10:34
@rolandjitsu did you tested if Dropzone it works for major browsers  inside a modal also?

**Comment by rolandjitsu** [comment] 2018-12-19 08:46
@jordiponsllaurado there shouldn't be any difference, unless the modal prevents some events. As I mentioned before, please open a new issue and provide an example illustrating the issue.

**Comment by rolandjitsu** [comment] 2018-12-19 10:31
@Shubham-S-Yadav https://github.com/react-dropzone/react-dropzone/pull/733 should fix the issue you described in Safari 11. Will be merged and released soon.

**Closed** 2018-12-22 16:15 UTC
Labels: bug
