### ISSUE TITLE
[BUG] isDragAccept and isDragReject won't work on Safari

### ISSUE THREAD

**Issue by habovh** [react-dropzone/react-dropzone#1266] opened 2023-01-17 22:21 UTC
**Describe the bug**
On Safari (tested with 16.2 on desktop), both `isDragAccept` and `isDragReject` boolean flags won't work and will always remain `false`. On the other hand, `isDragActive` works as intended.

Same code works on Chrome to provide visual feedback to the user when dragging is valid or invalid. Is this a known issue? Safari limitation?

**To Reproduce**
Minimal repro code:

```jsx
export const Dropzone = (props: Props) => {
  const { getRootProps, getInputProps, isDragActive, isDragAccept, isDragReject } = useDropzone({
    onDropAccepted: props.onChange,
    accept: { 'image/*': [] },
  })
  return (
    <div
      {...getRootProps()}
      className={cn(
        styles.wrapper,
        {
          [styles.dragging]: isDragAccept,
          [styles.rejecting]: isDragReject,
        },
      )}
    >
      <input {...getInputProps()} />
      <p>
        {!isDragActive && 'You can also drag and drop here'}
        {isDragAccept && "Drop it like it's hot"}
        {isDragReject && "One of these won't work" }
      </p>
    </div>
  )
}
```

**Expected behavior**
`isDragAccept` and `isDragReject` should update according to currently dragging state.

**Screenshots**

| Browser | State | Screenshot |
| --- | --- | --- |
| Both | Resting | ![both-resting](https://user-images.githubusercontent.com/4186230/213024857-cda8e40f-1ddb-479a-b970-a645fc6a0d11.png) |
| Chrome | Accept | ![chrome-accept](https://user-images.githubusercontent.com/4186230/213024873-4a17d828-dcee-44c7-96e0-4298372aa7a7.png) |
| Chrome | Reject | ![chrome-reject](https://user-images.githubusercontent.com/4186230/213024894-7699e811-5c32-4e06-9de1-50849cbede3b.png) |
| Safari | Accept | ![safari-accept](https://user-images.githubusercontent.com/4186230/213024905-cc665081-58df-4e7a-97a8-1d264e94eb58.png) |
| Safari | Reject | ![safari-reject](https://user-images.githubusercontent.com/4186230/213024918-7f0380c8-8ea0-4045-a80b-b0374f39ec10.png) |

As you can see, the text line is empty because the `!isDragActive` condition is correctly handled, but neither the accept or reject flags updated.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 16.2

**Comment by develth** [comment] 2023-03-15 10:45
Also recognized that in current Firefox on mac

**Comment by Birddle** [comment] 2023-03-17 08:11
Same problem, it doesn't work on my mac os in Safari, duckduckgo. 
According to https://react-dropzone.js.org/#section-accepting-specific-file-types I had guessed that this might be caused by not being able to match file suffixes or types correctly, but when I include all file types it still doesn't work. Now I don't know what to do.

**Comment by Birddle** [comment] 2023-03-24 13:03
Not any update?

**Comment by jeffjvick** [comment] 2023-03-29 06:41
We are having the same issue.  Works fine on Chrome, Firefox and Edge (all on a Mac), but not Safari 16.4.

The same issue as @habovh.  When you drag the file in Safari both isDragAccept and isDragRejected are false causing the interface to essentially go blank.  Everything works fine regarding uploading but the UI jumps all over the place as it's in an "impossible" state (both not accepted or rejected).

Has anyone achieved a work around other than check for the case of both false and assume that means isDragAccept should be true?

**Comment by jeffjvick** [comment] 2023-03-29 07:39
Looking further into the docs I see that this is a known issue with different browser implementations of the HTML5 File API and not an issue with this codebase per say. 

> Browser limitations
> Because of HTML5 File API differences across different browsers during the drag, Dropzone might not be able to detect whether the files are accepted or rejected in Safari nor IE.

We will probably need to remove the Accept/Reject status while the drag is active and just display a status after the drag.

**Comment by rolandjitsu** [comment] 2024-10-04 20:35
@jeffjvick thanks for the quote. That is correct, the behaviour may be different in every browser, and Safari is known to have some issues with file data during drag.

I don't think there's much we can do about it.

**Comment by rolandjitsu** [comment] 2024-11-03 13:21
I've tried to reproduce at https://react-dropzone.js.org/#section-accepting-specific-file-types in Safari 17.6 on macOS 12.7.6 but I cannot.

Given that validation is not consistent across browsers and it's a known issue (that we cannot fix), I'm gonna close this issue.

But if there's more info that could be provided, e.g. a codesandbox with more details, that could help reproduce the issue, please reopen and I'll have another look at it.

**Closed by rolandjitsu** 2024-11-03 13:21 UTC
Labels: bug
