### ISSUE TITLE
File open dialog allows everything, ignoring extensions specified in accept paramater

### ISSUE THREAD

**Issue by paulschreiber** [react-dropzone/react-dropzone#1164] opened 2022-03-23 22:23 UTC
**Describe the bug**
The file open dialog allows file of any type to be selected, ignoring extensions specified in the accept parameter. Likely related to #1141.

**To Reproduce**
1. Specify file extensions in your accept parameter, like so:
```js
  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: '.geojson,.json',
    multiple: false
  });
```

2. Click in the dropzone compoent.

You can see this problematic behavior here:
https://b5ree6.csb.app/

But if you use it inside codesandbox directly, it works (shows only .json/.geojson files)
https://codesandbox.io/s/react-dropzone-example-forked-b5ree6?file=/src/App.js

**Actual behavior**
The file open dialog lets you pick files of any time.

**Expected behavior**
The file open dialog lets you pick files with the `.geojson` and `.json` extensions.

**Additional context**
If you unhide the `<input>` tag with the browser inspector and click `Choose File`, the open dialog correctly allows only GeoJSON files.

If you look at [filePickerOptionsTypes](https://github.com/react-dropzone/react-dropzone/blob/master/src/utils/index.js#L183) you can see that it only accepts MIME types and not file extensions.

**Comment by rolandjitsu** [comment] 2022-03-26 05:12
@paulschreiber yes, this issue is related to https://github.com/react-dropzone/react-dropzone/issues/1141. So I'll close this one and track it there.

**Closed** 2022-03-26 05:12 UTC
Labels: bug, duplicate

**Comment by rolandjitsu** [comment] 2022-03-29 23:47
> @rolandjitsu is there a workaround you can recommend in the interim?

You can disable the FS access API with `useFsAccessApi: false`.

**Comment by VladimirMikulic** [comment] 2022-05-03 10:21
I also have this issue @rolandjitsu.
It doesn't work on the documentation either: https://react-dropzone.js.org/#section-accepting-specific-file-types

**Comment by rolandjitsu** [comment] 2022-05-03 12:46
@VladimirMikulic it was tracked in https://github.com/react-dropzone/react-dropzone/issues/1141 and there's been some changes to how you set the `accept` attribute. Please see [v14](https://github.com/react-dropzone/react-dropzone/releases/tag/v14.0.0).

**Comment by VladimirMikulic** [comment] 2022-05-03 15:00
Appreciate the fast reply @rolandjitsu. I am familiar with the new `accept` in v14.
However, new `accept` doesn't launch file picker on click. (dropping files works)
https://react-dropzone.js.org/#section-accepting-specific-file-types

**Comment by rolandjitsu** [comment] 2022-05-04 02:52
> Appreciate the fast reply @rolandjitsu. I am familiar with the new `accept` in v14. However, new `accept` doesn't launch file picker on click. (dropping files works) https://react-dropzone.js.org/#section-accepting-specific-file-types

`accept` is not supposed to trigger anything. Or maybe I didn't get what you are trying to say. Are you saying that clicking the dropzone doesn't trigger the file picker dialog to open? Because I cannot reproduce that on macOS 11.6.2, Chrome 99.0.

**Comment by VladimirMikulic** [comment] 2022-05-04 09:56
Sorry, my explanation was a bit unclear. 
After specifying `accept` parameter, clicking on the input field/area doesn't work anymore - no file picker. 
Dropping files in the area works though.

If I remove `accept` altogether or keep it with `useFsAccessApi: false`, only then it works. (Chrome 100, Ubuntu)

**Comment by rolandjitsu** [comment] 2022-05-04 09:58
> Sorry, my explanation was a bit unclear. After specifying `accept` parameter, clicking on the input field/area doesn't work anymore - no file picker. Dropping files in the area works though.
> 
> If I remove `accept` altogether or keep it with `useFsAccessApi: false`, only then it works. (Chrome 100, Ubuntu)

Could you add the `onError` callback and log the err? Maybe it throws.

**Comment by VladimirMikulic** [comment] 2022-05-05 07:43
I added `onError` callback - no errors thrown.
Does example in documentation work for you?: https://react-dropzone.js.org/#section-accepting-specific-file-types
(it doesn't work for me)

**Comment by rolandjitsu** [comment] 2022-05-06 08:41
> Does example in documentation work for you (click to upload)?: https://react-dropzone.js.org/#section-accepting-specific-file-types

Yes, it does.

What OS and browser are you using?

**Comment by VladimirMikulic** [comment] 2022-05-06 12:14
That's weird. I am on Ubuntu running Chrome 100.

**Comment by rolandjitsu** [comment] 2022-05-09 13:30
> That's weird. I am on Ubuntu running Chrome 100.

This could be a different issue as the option to specify file extensions alongside the MIME types has been released. What exactly is not working?

**Comment by VladimirMikulic** [comment] 2022-05-09 15:25
> What exactly is not working, was it same as before, the click not opening the file picker dialog when the accept is set?

Correct. The weirdest part is that this only occurs on Chrome.
It works on Firefox and even on Chromium based Brave browser.
No idea what could be the cause.
