### ISSUE TITLE
Incorrect File Types Displayed in React Dropzone 

### ISSUE THREAD

**Issue by GVSSri** [react-dropzone/react-dropzone#1363] opened 2024-07-04 11:53 UTC
When using the React Dropzone component, the file selection dialog is incorrectly displaying .text files in addition to the expected .txt and .csv files. The file selection dialog should only display .txt and .csv files.

Steps to Reproduce:

Implement React Dropzone in your project.
Configure the file types to include .txt and .csv.
Open the file upload dialog.

**Observed Behavior:**

The file upload dialog displays .txt, .csv, and .text files.

Expected Behavior:**

The file upload dialog should only display .txt and .csv files.

![29eae9de-0205-4b62-b005-52490b5fe9dc](https://github.com/react-dropzone/react-dropzone/assets/166494572/55805329-e46b-4a16-b707-aed6a3891ef1)

Below is the code 

<Dropzone multiple={false}
                                    acceptedFiles
                                    accept={
                                        fileType.toLowerCase() === 'flatfile'
                                            ? { 'text/plain': ['.txt'], 'text/csv': ['.csv'] }
                                            : { 'application/xml': ['.xml'] }
                                    }
                                    onDrop={async (acceptedFiles) => {
                                        const file = acceptedFiles[0];
                                        setFiles(file);
                                    }}>
                                    {({ getRootProps, getInputProps }) => (
                                        <section>
                                            <div className={classes.dropzone_area} {...getRootProps()}>
                                                <input {...getInputProps()}>
 					    </div>
                                        </section>
                                    )}
                                </Dropzone>
                                
Please let me know if you need any additional information or if there are further steps I should take to resolve this issue. Thanks

**Comment by mickelsonmichael** [comment] 2024-07-30 15:41
This appears to be because the util function `` merges the keys and the extensions into a single value for the `accept` attribute of the `<input type="file"/>` element. The browser then interprets the MIME type and includes all values it associates with the type.

So in your example, the `text/plain` MIME type includes the `.text` extension in the browser's opinion, so it is included automatically.

See [this line](https://github.com/react-dropzone/react-dropzone/blob/c36ab5bd8b8fd74e2074290d80e3ecb93d26b014/src/utils/index.js#L247) for the merge statement.

A workaround is to create a fake MIME type that the browser does not know how to interpret, which should _hopefully_ not have any impact on the UX at all. See the example below and note the `text/plain-fake` MIME type.

```js
<Dropzone multiple={false}
  acceptedFiles
  accept={fileType.toLowerCase() === 'flatfile'
    ? { 'text/plain-fake': ['.txt'], 'text/csv': ['.csv'] }
    : { 'application/xml': ['.xml'] }
  }
  //...
}}>
```

**Comment by rolandjitsu** [comment] 2024-11-01 12:28
@mickelsonmichael is on the right track. The `text/plain` is what makes the browser behave that way. An alternative would be to use an empty mime type with a list of file extensions to include. 

I think there was another issue reported that's related to this behaviour.

**Comment by rolandjitsu** [comment] 2024-11-03 11:42
Closing this as it's expected behaviour.

Also note that if you want to use only file extensions, during drag, `{isDragReject}` will be undetermined since the file name/extension cannot be read until the file(s) is dropped. So I recommend using mime types when possible.

**Closed by rolandjitsu** 2024-11-03 11:42 UTC
Labels: bug, notabug
