### ISSUE TITLE
onFileDialogCancel triggered on correct file selection

### ISSUE THREAD

**Issue by ignlopezsanchez** [react-dropzone/react-dropzone#1079] opened 2021-07-02 13:40 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
 When I select a valid file, the onFileDialogCancel is being triggered
**If the current behavior is a bug, please provide the steps to reproduce.**

https://codesandbox.io/s/magical-lalande-xd33e?file=/src/App.js

https://www.loom.com/share/be48a5d16d6048bea56ee5d9acc6e292

1. Click on the red p
2. console.log "cancel" should not be called as there is a valid file

**What is the expected behavior?**

onFileDialogCancel shouldn´t be called

macOS Big Sur version 11.4
Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by ronzip** [comment] 2021-08-16 10:03
Happening to me too. Is there any update on that issue?

**Comment by ronzip** [comment] 2021-08-16 14:35
BTW, it seems that the onFileDialogClosed is having a race condition with onDrop which can cause this issue above.

**Comment by rolandjitsu** [comment] 2021-09-14 00:10
I can confirm this is happening. @ronzip that sounds like a valid reason why this would be happening. Would you like to make a PR to fix it?

**Comment by rolandjitsu** [comment] 2022-01-30 04:12
Gonna attempt to fix this if possible.

**Comment by rolandjitsu** [comment] 2022-01-30 11:59
Hmm, it seems to be difficult to fix due to the nature of how the change event is triggered (larger files take longer to trigger the `onchange` evt, so the `onfocus` event on the window - which we use to trigger oncancel - is triggered way earlier). Gonna try to find some way to fix it, otherwise this will just be like that until the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) becomes a living standard (🤞 ).

**Comment by rolandjitsu** [comment] 2022-02-05 03:35
Closed by https://github.com/react-dropzone/react-dropzone/commit/3ad4f007d70401e1d9adbc93ba2dfd69cc8c2a27. This is the best I could do for now.

**Closed by rolandjitsu** 2022-02-05 03:35 UTC
Labels: bug, in progress

**Comment by bogdaniordachescu** [comment] 2023-07-14 14:16
Still having issues on Safari
