### ISSUE TITLE
iOS cannot support application/pdf and image/* MIME types even when specified

### ISSUE THREAD

**Issue by xuefanzhang** [react-dropzone/react-dropzone#627] opened 2018-07-12 00:13 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
**What is the current behavior?**
PDFs are grayed out / not selectable on iPhone devices even though accept="application/pdf,image/*" is specified. Works fine on android, desktop safari/chrome.

To reproduce, set accept to accept='image/*,application/pdf'. 

"application/pdf,audio/*" works fine, so does "application/pdf" alone. "application/pdf, image/png" for example breaks. This appears to be a combination of pdf and image.

**What is the expected behavior?**
PDF should be selectable

Could be the same issue as https://github.com/react-dropzone/react-dropzone/issues/538 (closed as not reproducible)

**Comment by xuefanzhang** [comment] 2018-09-13 22:07
bump

**Comment by ilovett** [comment] 2018-09-25 18:33
https://openradar.appspot.com/36726477

**Comment by rolandjitsu** [comment] 2018-10-13 10:12
@xuefanzhang I'm afraid that there is not much we can do on our side to fix this. As I explained in https://github.com/react-dropzone/react-dropzone/issues/653#issuecomment-429525418 and as @ilovett pointed out in his comment, this is a problem with inconsistent behaviour of file selection in mobile browsers as the [`accept`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept) property is proxied to the input directly.

I'm closing this, but feel free to reopen if you think you may have found a bug caused by this lib.

**Closed by rolandjitsu** 2018-10-13 10:12 UTC
