### ISSUE TITLE
[Firefox] isDragActive is wonky on text

### ISSUE THREAD

**Issue by Togrias** [react-dropzone/react-dropzone#911] opened 2019-11-13 19:14 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
isDragActive returns false when dragging over text. This bug is reproducible on Firefox but seems to be working properly on Chrome.

**If the current behavior is a bug, please provide the steps to reproduce.**

The codesandbox [example](https://codesandbox.io/embed/stupefied-kepler-btkpt) displays this behaviour. Simply drag a file over the text in the example and the border will turn white (instead of green) in some places, especially right above the words.

**What is the expected behavior?**
isDragActive should be true when dragging over any children.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment] 2019-11-14 02:47
I think this is related to https://github.com/react-dropzone/react-dropzone/issues/888.

**Comment by Togrias** [comment] 2019-11-14 04:21
It's a separate issue. This bug occurs even on older versions of react-dropzone (See material-ui-dropzone) where #888 worked properly.

But it might be a bug with Firefox... I can't reproduce it on Chrome or Safari.

**Comment by rolandjitsu** [comment] 2019-11-14 09:50
Ok, I will reopen. I don't have time to investigate though, so you're welcome to do so and make a PR.

**Comment by byoungb** [comment] 2019-11-22 16:30
I was able to fix this with CSS in Firefox, if you have no background and add `z-index:-1` to the p tag.

**Comment by ivzinoviev** [comment] 2019-11-24 11:06
Reproduced in FF 70.0.1. Fixed by removing `line-height` style from text.

**Comment by byoungb** [comment] 2019-11-24 19:31
> Reproduced in FF 70.0.1. Fixed by removing `line-height` style from text.

Not a bad solution but this is not great when text needs to wrap on smaller screen resolutions.

**Comment by rolandjitsu** [comment] 2019-11-25 01:14
I can confirm that there seems to be an issue in Firefox, unrelated to the issue I referenced initially. Might have something to do with the way we check if `ondragleave` evt happened on a child of the dropzone.

I'll try to spend a few minutes looking into it this week or over the weekend, but if anyone wants to look into it, feel free do to so and make a PR.

**Comment by remijean** [comment] 2020-01-24 13:06
Same problem with Chrome 79

**Comment by depiction** [comment] 2020-03-24 13:59
This is still an issue. The workarounds mentioned above didn't work for me.

**Closed** 2020-04-26 08:27 UTC
Labels: bug
