### ISSUE TITLE
TypeError: Cannot read property 'isEqualNode' of undefined

### ISSUE THREAD

**Issue by NunoCardoso** [react-dropzone/react-dropzone#766] opened 2019-02-22 09:26 UTC
Hi. I have a react-dropzone thatbefore was letting users opening the file upload dialog by pressing te spacebar, but I checked now and it doesn't work.

I updated to 8.2.0, still no avail. I am attaching a screenshot of the console error.
I see that the code fails in a code snippet that you guys added in December. 

Not sure why it fails on my end, but maybe protect it with a 

`if (this.node && !_this.node.isEqualNode(evt.target))` 

might solve it?

**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Can't open the file dialog by pressing spacebar 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. focus on the Dropzone component
2. press spacebar to open the file upload dialog

**What is the expected behavior?**

Expecting the file dialog to open. It does not, as there is a console error.

![reactdropzone](https://user-images.githubusercontent.com/525528/53232551-9afaea00-368b-11e9-8788-3b065169fe0f.jpg)

**Comment by rolandjitsu** [comment] 2019-02-22 10:37
@NunoCardoso we cannot reproduce this on [react-dropzone.js.org](https://react-dropzone.js.org/). When the dropzone is in focus, opening the file select dialog with keydown events (SPACE/ENTER) works just fine.

You will have to provide a reproducible example, otherwise we cannot help you.

**Comment by goodoldneon** [comment] 2019-02-26 22:37
I'm experiencing the same issue. It happens when I put a `ref` on a child of `<Dropzone>`.

[Codepen](https://codepen.io/goodoldneon/pen/MxYBQV)

**Comment by rolandjitsu** [comment] 2019-02-26 22:43
@goodoldneon right, that's because you're overriding the ref that `getRootProps()` sets.

Can you describe what is your use case? Maybe we need to think about exposing the ref somehow.

**Comment by goodoldneon** [comment] 2019-02-26 22:44
Sorry, I edited my comment before you finished your response. I don't think you guys need to change anything, besides maybe warning about this in the docs.

**Comment by rolandjitsu** [comment] 2019-02-27 06:46
@goodoldneon Yeah, I saw it now 😄 

Well, the docs are a bit vague, to be honest. So I should probably be more specific about the fact that you cannot bind a ref to the same node where the dropzone is bound.

**Comment by NunoCardoso** [comment] 2019-02-28 12:05
Sorry for not answering your question, @rolandjitsu .

That is correct, I have the Dropzone inside a Droppable from react-beautiful-dnd because reasons :), and I add a ref. Still, changing the line to `if (this.node && !_this.node.isEqualNode(evt.target))`  works. You have to double check however if that leads to lost functionality somehow.

Let me know if you need a sample of my React component to reproduce the error and double-check the fix.

**Comment by rolandjitsu** [comment] 2019-02-28 14:29
@NunoCardoso this will change anyway in the next major version.

We're working on using the hooks API. You will also be able to get the ref to the dropzone and input elements with the new release.

I will close this now, but please let me know if you have any other issues.

**Closed by rolandjitsu** 2019-02-28 14:29 UTC
