### ISSUE TITLE
Using open() on Click does not work in some cases

### ISSUE THREAD

**Issue by sdancer75** [react-dropzone/react-dropzone#1349] opened 2024-03-24 19:26 UTC
**Describe the bug**

Using a modified version of the official example below to **open** the File Dialog Programmatically in my ReactJs project, it appears to be functioning properly under my local machine.

However, when I upload the code to AWS (Linux) server (non-secured) this functionality does not work. 

I tested it, with all major browsers I had. 

```
import React from 'react';
import {useDropzone} from 'react-dropzone';

function Dropzone(props) {
  const {getRootProps, getInputProps, open, acceptedFiles} = useDropzone({
    // Disable click and keydown behavior
    noClick: true,
    noKeyboard: true
  });

  const files = acceptedFiles.map(file => (
    <li key={file.path}>
      {file.path} - {file.size} bytes
    </li>
  ));

  return (
    <div className="container">
      <div {...getRootProps({className: 'dropzone'})}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here</p>
        <button type="button" onClick={open}>
          Open File Dialog
        </button>
      </div>
      <aside>
        <h4>Files</h4>
        <ul>{files}</ul>
      </aside>
    </div>
  );
}

<Dropzone />
```

**To Reproduce**
Run the Opening File Dialog Programmatically at https://react-dropzone.js.org/#section-basic-example

**Expected behavior**
To open the file dialog

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser [Firefox, chrome]
 - Version [Firefox 124.01, Chrome 123.0.63]

**Smartphone (please complete the following information):**

**Comment by sdancer75** [comment] 2024-03-26 09:16
It seems that the problem is related to the secure content. I am not currently using SecureContent in my AWS

` const fsAccessApiWorksRef = useRef(typeof window !== 'undefined' && window.isSecureContext && useFsAccessApi && canUseFileSystemAccessAPI());`
 
so the check is returning false and skips the **showOpenFilePicker**. So the question here why it should be secured to pick a file from the local computer?

```
   // Fn for opening the file dialog programmatically
   const openFileDialog = useCallback(() => {
      // No point to use FS access APIs if context is not secure
      // https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#feature_detection
      if (fsAccessApiWorksRef.current) {
         dispatch({ type: 'openDialog' });
         onFileDialogOpenCb();
         // https://developer.mozilla.org/en-US/docs/Web/API/window/showOpenFilePicker
         const opts = {
            multiple,
            types: pickerTypes,
         };
```

**Comment by todorpr** [comment] 2024-04-09 11:42
I want to report the same issue - click doesn't open the window to select file. In Safari it works fine, but not in Chrome.

**Comment by george-eucare** [comment] 2024-04-24 09:10
same issue , Safari works fine, but not in Chrome.

**Comment by BrenoVital** [comment] 2024-10-04 20:48
same issue

**Comment by rolandjitsu** [comment] 2024-10-07 20:04
@sdancer75 is correct. And it's not something we can fix. Right now, we've disabled the use of file access API by default and we use the traditional input click method, unless you opt in to use the new API.

I will go ahead and close this for now as the behaviour described in the issue is expected and the fix would be to disable the use of file access API.

**Closed by rolandjitsu** 2024-10-07 20:04 UTC
Labels: bug
