### ISSUE TITLE
The Doc-Website is not worlking: https://react-dropzone.js.org/

### ISSUE THREAD

**Issue by taraskolba** [react-dropzone/react-dropzone#905] opened 2019-11-05 09:42 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.
1.
1.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by rolandjitsu** [comment] 2019-11-05 09:44
Duplicate of https://github.com/react-dropzone/react-dropzone/issues/887.

**Closed by rolandjitsu** 2019-11-05 09:44 UTC
