### ISSUE TITLE
react-dropzone.js.org is dead.

### ISSUE THREAD

**Issue by saysmaster** [react-dropzone/react-dropzone#893] opened 2019-10-16 07:49 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Navigating to https://react-dropzone.js.org/ shows empty page. In console you can see this
```
bundle.21ea12b5.js:13 Uncaught TypeError: Cannot read property 'F' of undefined
    at f (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at n (bundle.21ea12b5.js:13)
    at bundle.21ea12b5.js:13
    at Object.<anonymous> (bundle.21ea12b5.js:13)
    at __webpack_require__ (bundle.21ea12b5.js:1)

```
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Navigate to https://react-dropzone.js.org/
2. Open console in dev tools

**What is the expected behavior?**
Navigating to https://react-dropzone.js.org/ should show the documentation of react-dropzone

**Comment by rolandjitsu** [comment] 2019-10-16 07:51
Duplicate of https://github.com/react-dropzone/react-dropzone/issues/887. Please search through the current issues next time you open one.

**Closed by rolandjitsu** 2019-10-16 07:51 UTC
