### ISSUE TITLE
[BUG] Import .pfx file

### ISSUE THREAD

**Issue by DevNF** [react-dropzone/react-dropzone#1169] opened 2022-04-05 12:58 UTC
**Describe the bug**

**To Reproduce**

3. Select file .pfx ('application/x-pkcs12 or 'application/pkcs12)

**Expected behavior**
When selecting a file of type 'application/x-pkcs12' or 'application/pkcs12', when checking the type of imported file it is empty. (This does not happen when the file is dragged, only when selected)
Below I will leave an image of when I drag and when I select the file

**Screenshots**
When select:
![image](https://user-images.githubusercontent.com/90803174/161757909-1877dd6c-450c-4aa7-8351-9b2b5fed970e.png)
![image](https://user-images.githubusercontent.com/90803174/161758067-285301f5-10ab-4cd3-a6d2-344418e8c14a.png)

When drag:
![image](https://user-images.githubusercontent.com/90803174/161758292-f971f6f0-e09b-4621-ac08-5df7dee02e53.png)
![image](https://user-images.githubusercontent.com/90803174/161758354-fb04b168-bee7-46c3-861c-7c25c921d489.png)

If you also notice, in the first image it shows all the files to select, and my input contains the accept property, that is, before I updated to the latest version of react-drozone, it respected the accept, now it no longer and all files become visible

react-dropzone version: 12.0.4

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 100.0.4896.75

**Comment by rolandjitsu** [comment] 2022-05-02 02:02
@DevNF it's not clear from the description what is the issue. Is it that the file type is not provided when selecting using the file picker or that the `accept` property doesn't work as expected?

Also, could you upgrade to v14 and let me know if whatever issues you're describing still persists?

**Comment by DevNF** [comment] 2022-05-02 16:44
Both. the file type is not provided and the accept property is not working as expected! In version 14 still the same errors

**Comment by rolandjitsu** [comment] 2022-05-03 01:58
> Both. the file type is not provided and the accept property is not working as expected! In version 14 still the same errors

Note that there are some changes in how the `accept` property is passed to the dropzone now.

**Comment by rolandjitsu** [comment] 2022-05-03 03:11
Also, does this (the missing file type) happen on our official docs site: https://react-dropzone.org/?

Because I just tested on Linux (Debian/Raspbian OS) with an old Chromium version and the file type works just fine:

https://user-images.githubusercontent.com/1479737/166395645-94dbc3e6-9c84-4237-b315-ce6e04bb5215.mp4

But that may be because the new FS access API is not being used. So in your case it's likely it is used and there's something off with the file type. I will need to investigate further to see if it's an issue with the API or our impl.

**Comment by rolandjitsu** [comment] 2022-05-03 03:24
I can confirm that this is an issue with the FS access API. 

If you run:
```js
async function getFile() {
  // open file picker
  try {
    const [fileHandle] = await window.showOpenFilePicker();
    const canRead = verifyPermission(fileHandle);

    if (canRead) {
      const fileData = await fileHandle.getFile();
      console.log(fileData);
    } else {
      console.warn('no permissions to read file')
    }
  } catch (e) {
    console.error(e)
  }
}

async function verifyPermission(fileHandle, withWrite) {
  const opts = {};
  // Check if we already have permission, if so, return true.
  if (await fileHandle.queryPermission(opts) === 'granted') {
    return true;
  }

  // Request permission to the file, if the user grants permission, return true.
  if (await fileHandle.requestPermission(opts) === 'granted') {
    return true;
  }

  // The user did not grant permission, return false.
  return false;
}

getFile()
```

You'll notice that the file doesn't have a type set:
```
File {name: 'cert.pfx', lastModified: 1651547764348, lastModifiedDate: Tue May 03 2022 11:16:04 GMT+0800 (Singapore Standard Time), webkitRelativePath: '', size: 3229, …}
lastModified: 1651547764348
lastModifiedDate: Tue May 03 2022 11:16:04 GMT+0800 (Singapore Standard Time) {}
name: "cert.pfx"
size: 3229
type: ""
webkitRelativePath: ""
```

You may want to report this on the chromium channel.

In the meantime, we could fix it by adding the file extension to [file-selector](https://github.com/react-dropzone/file-selector/blob/76a4033d344d1383aeb5ff628b1749ed6334d5f5/src/file.ts#L1).

**Comment by rolandjitsu** [comment] 2024-10-03 19:37
I'm going to go ahead and close this issue. We've disabled the use of file access API by default and it doesn't seem like the author of the issue is interested in adding the file extension to [file-selector](https://github.com/react-dropzone/file-selector/blob/76a4033d344d1383aeb5ff628b1749ed6334d5f5/src/file.ts#L1).

**Closed by rolandjitsu** 2024-10-03 19:37 UTC
Labels: bug, needs investigation, needs example
