### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by mintran** [react-dropzone/react-dropzone#908] opened 2019-11-12 08:46 UTC
The demo site is inaccessible. Can you check it? Thanks!

**Comment by sakharovsergey** [comment] 2019-11-12 11:06
```
bundle.c23f182e.js:13 Uncaught TypeError: Cannot read property 'F' of undefined
    at f (bundle.c23f182e.js:13)
    at Object.<anonymous> (bundle.c23f182e.js:13)
    at n (bundle.c23f182e.js:13)
    at Object.<anonymous> (bundle.c23f182e.js:13)
    at n (bundle.c23f182e.js:13)
    at Object.<anonymous> (bundle.c23f182e.js:13)
    at n (bundle.c23f182e.js:13)
    at bundle.c23f182e.js:13
    at Object.<anonymous> (bundle.c23f182e.js:13)
    at __webpack_require__ (bundle.c23f182e.js:1)
```

**Comment by rolandjitsu** [comment] 2019-11-12 11:07
Duplicate of https://github.com/react-dropzone/react-dropzone/issues/887.

**Closed by rolandjitsu** 2019-11-12 11:07 UTC
