### ISSUE TITLE
Example link broken

### ISSUE THREAD

**Issue by rapsalands** [react-dropzone/react-dropzone#901] opened 2019-10-29 21:58 UTC
https://react-dropzone.js.org/

Link for examples and demo is broken. Page shows white blank screen.
Tried on Google Chrome build 77.0.3865.75.

Console errors are as follows.

```
bundle.28a8f68f.js:13 Uncaught TypeError: Cannot read property 'F' of undefined
    at f (bundle.28a8f68f.js:13)
    at Object.<anonymous> (bundle.28a8f68f.js:13)
    at n (bundle.28a8f68f.js:13)
    at Object.<anonymous> (bundle.28a8f68f.js:13)
    at n (bundle.28a8f68f.js:13)
    at Object.<anonymous> (bundle.28a8f68f.js:13)
    at n (bundle.28a8f68f.js:13)
    at bundle.28a8f68f.js:13
    at Object.<anonymous> (bundle.28a8f68f.js:13)
    at __webpack_require__ (bundle.28a8f68f.js:1)
```

**Comment by rolandjitsu** [comment] 2019-10-30 01:25
Duplicate of https://github.com/react-dropzone/react-dropzone/issues/887.

**Closed** 2019-11-05 09:45 UTC
