### ISSUE TITLE
[BUG] Mobile Uploads Don't Work when in a Portal

### ISSUE THREAD

**Issue by joelzimmer** [react-dropzone/react-dropzone#1196] opened 2022-05-19 16:26 UTC
**Describe the bug**
On iOS, embedding the button to Upload a File in a `Portal` causes the list of `acceptedFiles` to not be populated, meaning files can't be uploaded

**To Reproduce**

This can be reproduced on https://codesandbox.io/s/react-dropzone-example-forked-qff7dm?file=/src/App.js or by locally cloning https://github.com/joelzimmer/dropzone-portal (to run it on the iOS simulator, it is a Create React App, so can be run by `npm i && npm run start)

1. Go to https://codesandbox.io/s/react-dropzone-example-forked-qff7dm?file=/src/App.js or run https://github.com/joelzimmer/dropzone-portal and open it on an iOS device/Simulator
2. Click on the "Open Popover Button"
3. Click the "Upload" button
4. Select files
5. Note that the list of files is not populated

**Expected behavior**
The list of files should be populated by react-dropzone

**Screenshots**
Desktop upload succeeding in create-react-app example:

https://user-images.githubusercontent.com/156871/169350449-516bf5de-5a62-40f1-920f-533d73e228c0.mp4

iOS upload not showing any files in create-react-app example:

https://user-images.githubusercontent.com/156871/169350523-f080979f-02ca-4ea2-93d8-cf6473bf0426.mp4

**Desktop**
 - OS: macOS
 - Browser: Chrome
 - Version: 101

**Smartphone**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15
 - Browser: Safari
 - Version: 16

**Additional context**
N/A

**Comment by joelzimmer** [comment] 2022-05-25 17:57
Hi folks! Just wanted to bump this and see if anyone has a moment to look at it

**Comment by najihmld** [comment] 2022-09-01 04:43
on android device also have the same problem

**Comment by udayan46** [comment] 2022-09-09 05:18
Any update on this , seems like react is not accepting the video for iphone and ipad

**Comment by guerillarealty** [comment] 2022-09-22 17:15
I'm having the same issue with safari on iphone (v15+)

**Comment by hsjakobsen** [comment] 2023-01-11 11:09
I'm seeing this issue as well. This limitation seriously challenges my UI design.

**Comment by hardcoderrsl** [comment] 2023-01-26 07:04
dropzone is working fine when uploading from desktop or androids. but when iPhone- nothing is uploaded

**Comment by daxiang28** [comment] 2023-01-31 04:15
FWIW, setting `noClick: true` allowed me to upload on mobile. I had to manually add an 'onClick' to a wrapper to replicate the onClick/tap action

**Comment by hsjakobsen** [comment] 2023-01-31 08:23
> FWIW, setting `noClick: true` allowed me to upload on mobile. I had to manually add an 'onClick' to a wrapper to replicate the onClick/tap action

I can confirm that this works on mobile. Excellent workaround.

My code looks like this:


```
 const { getInputProps, isDragAccept, isDragReject, getRootProps, open } = useDropzone({ noClick: true}}
 
 <div
   {...getRootProps({
     className: clsx('dropzone-container', `dropzone-border-${getBorderColor()}`),
   })}
   onClick={open} >
   <input {...getInputProps()} />
   <Icon name="cloud upload" size="big" className="dropzone-icon" />
   <p>Drag 'n' drop your images here, or click to select them.</p>
 </div
```

**Comment by terryjiang2020** [comment] 2023-06-25 04:22
`open` with `onClick` still not work for me. What I did to solve it is to make a conditional render to render a native input field on mobile (which only allows click to trigger its events) rather than using Dropzone.

I guess no one is going to use drag and drop feature on mobile end anyway.

**Comment by ilyaskarim** [comment] 2023-10-25 15:50
@terryjiang2020 can you show how your code looks like?

**Comment by ahb10** [comment] 2023-11-18 12:08
> FWIW, setting `noClick: true` allowed me to upload on mobile. I had to manually add an 'onClick' to a wrapper to replicate the onClick/tap action

Definitely a great help. I was going to use a different package or simple upload button for mobile screens.

Also @hsjakobsen thanks for the hint

**Comment by rolandjitsu** [comment] 2024-10-03 19:52
@daxiang28 thanks for sharing the workaround. It sounds like the issue has to do with even bubbling.

I could still try to replicate the issue to see what exactly is going on, but I cannot promise it'll be anytime soon.

**Comment by kamilaqz** [comment] 2024-10-31 14:14
noClick=true worked like a charm. Thanks, guys!!!!!!!

**Comment by rolandjitsu** [comment] 2024-11-02 14:36
Gonna close this for now as it seems like `noClick` is the answer here.

**Closed by rolandjitsu** 2024-11-02 14:36 UTC
Labels: bug
