### ISSUE TITLE
[BUG] Clicking the dropzone area won't open the choose file dialog on newest Chrome

### ISSUE THREAD

**Issue by xpyx** [react-dropzone/react-dropzone#1239] opened 2022-09-15 06:09 UTC
Hello and thanks for the great hook. I came across this bug this morning and thought that it should be reported.

**Describe the bug**
When clicking the dropzone, the dialog for choosing files does not appear. This might be due to browser update. Yesterday the click to open dialog was working as expected.

**To Reproduce**

```
    const { getRootProps, getInputProps } = useDropzone({
        validator: duplicateFileValidator,
        onDrop: (files: File[]) => {
            const uniques = Array.from(new Set(filesArray))
            setFilesArray([...uniques, ...files])
        },
        accept: acceptedFileTypes,
        maxSize: maxSizeBytes,
    })
```

```
<div className={styles.dropZone} {...getRootProps()} id="upload-file">
                    <input {...getInputProps()}/>
</div>
```

**Expected behavior**
A dialog for choosing a file should open. Works as expected in Firefox.

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1 
 - Chrome 105.0.5195.102 (Official Build) (arm64)
 - React-dropzone version: `11.4.2`
 
 I tried it also on the latest `14.2.2`, but same bug there.

**Comment by immutable-pro** [comment] 2022-09-15 09:46
I can confirm I am seeing the same behavior, using `14.2.2`. It works on Firefox `104.0.2` and Gnome Web Browser `42.4`, but not in Chrome` 105.0.5195.125`

**Comment by ahmedmukhtar1133** [comment] 2022-09-27 15:07
**Facing same issue:**
**OS:** `macOS 12.5.1`
**Chrome** `105.0.5195.125` (Official Build) (arm64)

**Comment by nettum** [comment] 2022-10-04 12:50
I can confirm that I got the same issue in chrome when the `accept`-option is set.

Not working on `Google Chrome Version 106.0.5249.61 (Official Build) (64-bit)`.
Working on `Firefox Browser 105.0.1 (64-bit)`. 
Both tests on `Ubuntu 22.04.1 LTS`.

Example code:
```
  const {
    acceptedFiles,
    fileRejections,
    getRootProps,
    getInputProps,
    isDragActive
  } = useDropzone({
    accept: {
      'image/jpeg': [],
      'image/png': [],
    },
    maxSize: 10485760
  });
```

If I remove the `accept`-option from the hook it also works in chrome, e.g:
```
  const {
    acceptedFiles,
    fileRejections,
    getRootProps,
    getInputProps,
    isDragActive
  } = useDropzone({
    maxSize: 10485760 // 10MB
  });
```

**Comment by merveillevaneck** [comment] 2022-10-05 15:05
can also confirm that this fails on latest chrome version. tested safari as well and that seems to be working fine. So must be something api related on google chrome's side.

**Comment by BranislavLazic** [comment] 2022-10-12 08:35
Hi, the issue is still reproducible even if I remove `accept` option. Browser: Chrome 105.0.5195.125 (Official Build) (arm64).

**Comment by Egr711** [comment] 2022-10-14 19:40
Can confirm the same was happening in Chrome `105.0.5195.125` 
Was having the same issue. upgrading to version 14.2.3 and updating chrome to latest `106.0.5249.119` fixed it

**Comment by panta82** [comment] 2023-08-04 22:52
Disabling `useFsAccessApi` worked for me.

**Comment by dahyeyudev** [comment] 2023-08-14 05:55
I was having this same problem in Chrome 115.0.5790.114 (arm64) and
updating chrome to latest version 115.0.5790.170 (arm64) fixed this problem.

**Comment by actuallymentor** [comment] 2023-09-06 09:26
Can confirm this issue, updating to `116.0.5845.163` did NOT solve the issue.

**Comment by ndvo** [comment] 2023-11-03 17:45
Disabling `useFsAccessApi` worked for me as well.

**Comment by rolandjitsu** [comment] 2024-10-03 20:33
Gonna close this as the file access API is experimental, thus unstable, and we've made it false by default.

**Closed by rolandjitsu** 2024-10-03 20:33 UTC
Labels: bug
