### ISSUE TITLE
[BUG]  drag & drop or select doesn't work on mobile device 

### ISSUE THREAD

**Issue by mahbubhasanhira** [react-dropzone/react-dropzone#1276] opened 2023-02-19 09:05 UTC

**Comment by iwasrobbed** [comment] 2023-06-19 16:26
Be sure to see https://github.com/react-dropzone/react-dropzone/issues/1196

especially re: using `open` to handle this on mobile https://github.com/react-dropzone/react-dropzone/blob/master/examples/file-dialog/README.md

**Comment by KutnerUri** [comment] 2024-05-15 15:37
yes - it's related to the label container. When I replaced the `<label>` with `<div>`, it's now working.
I think there is a fix to prevent duplicated dialogs in windows that misbehaves in mac

**Comment by rolandjitsu** [comment] 2024-11-02 13:34
@mahbubhasanhira the least you could have done is provide some description in your issue. You get a sample when you open an issue, just fill that in.

@iwasrobbed and @KutnerUri thanks for providing some possible solutions/insight. But without more context on what the author is experiencing, it's difficult to tell what the issue is.

For now, I'm going to close this.

**Closed by rolandjitsu** 2024-11-02 13:34 UTC
Labels: bug
