### ISSUE TITLE
I cannot access the document

### ISSUE THREAD

**Issue by TonyaQi** [react-dropzone/react-dropzone#909] opened 2019-11-12 13:45 UTC
emmm ,
https://react-dropzone.js.org.
This website is not accessible

**Comment by rolandjitsu** [comment] 2019-11-12 14:20
Please try to search through current issues before opening new ones. Duplicate of https://github.com/react-dropzone/react-dropzone/issues/887.

**Closed by rolandjitsu** 2019-11-12 14:20 UTC
