### ISSUE TITLE
Clicking inner element still shows file picker when noClick is used

### ISSUE THREAD

**Issue by gjj** [react-dropzone/react-dropzone#1013] opened 2020-09-28 06:41 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

When using `noClick` on an inner element, it does not prevent the parent element's file picker from showing. I actually posted a [question on SO](https://stackoverflow.com/questions/64091060/react-dropzone-prevent-inner-element-from-showing-file-picker) but after thinking about it, I'm not sure if it's because it's more of a bug?

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Copy the following codes and paste into the [View Code](https://react-dropzone.js.org/#section-event-propagation) section
```javascript
import React from 'react';
import {useDropzone} from 'react-dropzone';

function Dropzone(props) {
  const {getRootProps, getInputProps, open, acceptedFiles} = useDropzone({
    // Disable click and keydown behavior
    noKeyboard: true
  });

  const files = acceptedFiles.map(file => (
    <li key={file.path}>
      {file.path} - {file.size} bytes
    </li>
  ));

  return (
    <div className="container">
      <div {...getRootProps({className: 'dropzone'})}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here</p>
        <InnerButton />
      </div>
      <aside>
        <h4>Files</h4>
        <ul>{files}</ul>
      </aside>
    </div>
  );
}

function InnerButton(props) {
  const { getRootProps } = useDropzone({ noClick: true }); // doesn't stop the parent's input file picker

  return (
    <button {...getRootProps()} type="button">
      This button should not open the file picker
    </button>
  );
}

<Dropzone />
```
2. Click on the button
3. The native file picker shows up as the inner button's `noClick` does not prevent the outer dropzone's file picker from showing

**What is the expected behavior?**

I'd think that when using `noClick` on an inner element, it should not show the native file picker. While using `stopPropagation` works for me, I've read here https://github.com/react-dropzone/react-dropzone/issues/541#issuecomment-475941841 that it's discouraged and `noClick` should be used. However, it doesn't work in the above example.

So I'm not exactly sure if it's intended behaviour?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

`react-dropzone`'s version is `11.0.1`

**Comment by rolandjitsu** [comment] 2020-11-08 04:17
@gjj there's no way around it. You have to use `stopPropagation()` to stop the event from bubbling up the DOM. Your other option is to use `noClick` on the parent as well.

`noClick` only disables opening the file selector when clicking on the dropzone node. It does not prevent the event from bubbling.

I'm going to close this issue now as there's not much we can do. The only thing we can do is to provide a `noClickBubbling` option that calls `stopPropagation()`, but the user can already do that.

**Closed by rolandjitsu** 2020-11-08 04:17 UTC

**Comment by hanihusam** [comment] 2022-07-29 04:18
> @gjj there's no way around it. You have to use `stopPropagation()` to stop the event from bubbling up the DOM. Your other option is to use `noClick` on the parent as well.
> 
> `noClick` only disables opening the file selector when clicking on the dropzone node. It does not prevent the event from bubbling.
> 
> I'm going to close this issue now as there's not much we can do. The only thing we can do is to provide a `noClickBubbling` option that calls `stopPropagation()`, but the user can already do that.

Hi, I got a kinda this issue on Chrome.

So, I use `open` and provide `noClick`. It works perfectly except on Chrome. The issue is `event` arg/param from the `onDropAccepted` function return `null`.

Do you know why this happens?

**Comment by d-reader-josip** [comment] 2023-09-21 19:11
@hanihusam this is a long shoot from my side but... do you know if you managed to find a solution/answer to your question?
