### ISSUE TITLE
onFileDialogCancel triggered on correct file selection

### ISSUE THREAD

**Issue by Akramhar** [react-dropzone/react-dropzone#807] opened 2019-03-27 21:29 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
onFileDialogCancel is triggered even when a file is correctly selected in the file dialog

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's the [sandbox](https://codesandbox.io/embed/lyrqjp7yx9)

**What is the expected behavior?**
From what I have understood onFileDialogCancel should not be triggered if a file is correctly selected

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
"react-dropzone": "^10.0.6"
browser: google chrome Version 73.0.3683.86 (used to run codesandbox too)
os: windows10

Apologies in case I missed something super obvious :)

**Comment by rolandjitsu** [comment] 2019-03-28 01:23
@Akramhar I just tried the example and it works as expected. The `onFileDialogCancel` is called when you cancel the dialog (hit the cancel button or press ESC), regardless of files being selected. However, it does not get called if you click `Open`.

I hope this clears the confusion.

**Comment by Akramhar** [comment] 2019-03-28 02:07
Here's the console when I hit open on that example:
![image](https://user-images.githubusercontent.com/3996749/55124467-b1f28900-50dc-11e9-8d3b-126fa88aadf2.png)

**Comment by Akramhar** [comment] 2019-03-28 02:13
I'm testing it on another machine that has windows7 and the problem doesn't seem to appear.

**Comment by rolandjitsu** [comment] 2019-03-28 02:15
I tried it from my macOS 10.14. I don't see the cancel log. I don't have a windows machine unfortunately. I will try to use SauceLabs to test it later.

**Comment by Akramhar** [comment] 2019-03-28 02:20
Oki, thank you very much :)
I will try to do more tests too.

**Comment by avatar5555555** [comment] 2019-05-26 13:57
In my case `onFileDialogCancel` is triggered if I open dialog programatically (Safari and Chrome). The next snippet helped me solve the issue.
```
const handleOpen = useCallback(
    (e: React.FormEvent<HTMLInputElement>) => {
      e.stopPropagation()
      open()
    },
    [open]
  )
```

**Comment by rolandjitsu** [comment] 2019-07-21 10:20
Closing this as I cannot really replicate the issue.

**Closed by rolandjitsu** 2019-07-21 10:20 UTC

**Comment by welcometochristown** [comment] 2021-07-07 01:28
I had this same issue which was intermittent. I believe the issue was being caused by the setTimeout that checks for if any files have been selected when the form becomes inactive. When I increased the time out the issue was resolved.

![image](https://user-images.githubusercontent.com/17158437/124686362-fd419780-dea0-11eb-99c9-742883f17216.png)

**Comment by bogdaniordachescu** [comment] 2023-07-14 14:11
I am having the same problem with latest version, for safari on mac OS. Cannot select files, this is triggered with selected files. Do you have any fix for this, or idea?
