### ISSUE TITLE
isDragAccept broken in Chrome due to #878

### ISSUE THREAD

**Issue by emrosenf** [react-dropzone/react-dropzone#895] opened 2019-10-16 18:10 UTC
- [x] I found a bug

**What is the current behavior?**

[utils/index.js line 10](https://github.com/react-dropzone/react-dropzone/commit/c8a7322c3f96b530a5a8d6c02562518aa50e0072#diff-8968c62593320351ced6a0ef776ef599L10) Does not account for the possibility that `file.size` is `undefined`.

```js
export function fileMatchSize(file, maxSize, minSize) {
  return file.size <= maxSize && file.size >= minSize
}
```

A [DataTransferItem](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem) does not have the `size` property.

Therefore the (default) comparison will be `undefined <= Infinity && undefined >= 0` which is false, and so `isDragAccept` will always be false.

This bug was introduced in #878 which was a fix for #861 

Using latest Chrome: 77.0.3865.120 (64-bit) on OSX 10.14.6

**Comment by rolandjitsu** [comment] 2019-10-17 10:40
Duplicate of https://github.com/react-dropzone/react-dropzone/issues/888.

**Closed by rolandjitsu** 2019-10-17 10:40 UTC
