### ISSUE TITLE
@types/react@16.9.46: Types of property 'style' are incompatible

### ISSUE THREAD

**Issue by ldiqual** [react-dropzone/react-dropzone#1000] opened 2020-08-15 17:57 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

Typescript errors out when building the react-dropzone example, using the latest version of @types/react

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Upgrade @types/react to 16.9.46
2. Use react-dropzone 11.0.3
3. Run example code: 

```
function MyDropzone() {
  const onDrop = useCallback(acceptedFiles => {
    // Do something with the files
  }, [])
  const {getRootProps, getInputProps, isDragActive} = useDropzone({onDrop})

  return (
    <div {...getRootProps()}>
      <input {...getInputProps()} />
      {
        isDragActive ?
          <p>Drop the files here ...</p> :
          <p>Drag 'n' drop some files here, or click to select files</p>
      }
    </div>
  )
}
```

Typescript fails with the following errors:

```
string | number | string[] | undefined; suppressContentEditableWarning?: boolean | undefined; ... 249 more ...; onTransitionEndCapture?: ((event: TransitionEvent<...>) => void) | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: Element[]; refKey?: string | undefined; defaultChecked?: boolean | undefined; defaultValue?: string | number | string[] | undefined; suppressContentEditableWarning?: boolean | undefined; ... 249 more ...; onTransitionEndCapture?: ((event: TransitionEvent<...>) => void) | undefined; }' is not assignable to type 'HTMLAttributes<HTMLDivElement>'.
    Types of property 'style' are incompatible.
      Type 'import("/Users/ldiqual/Siteline/siteline/node_modules/@types/react/index").CSSProperties | undefined' is not assignable to type 'React.CSSProperties | undefined'.
        Type 'import("/Users/ldiqual/Siteline/siteline/node_modules/@types/react/index").CSSProperties' is not assignable to type 'React.CSSProperties'.
          Types of property 'appearance' are incompatible.
            Type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "none" | "button-bevel" | "checkbox" | "listbox" | "menulist" | "menulist-button" | "meter" | "progress-bar" | "push-button" | ... 7 more ... | undefined' is not assignable to type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "none" | "checkbox" | "listbox" | "menulist" | "menulist-button" | "meter" | "progress-bar" | "push-button" | "radio" | ... 6 more ... | undefined'.
              Type '"button-bevel"' is not assignable to type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "none" | "checkbox" | "listbox" | "menulist" | "menulist-button" | "meter" | "progress-bar" | "push-button" | "radio" | ... 6 more ... | undefined'.
```

This happens for @types/react v16.9.44 to v16.9.46. Does not affect v16.9.43.

**What is the expected behavior?**

Typescript successfully compiles the example code.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

**Comment by Naspo88** [comment] 2020-09-03 10:47
Have you solved it? I'm having the same problem.

**Comment by rolandjitsu** [comment] 2020-09-05 12:11
@ldiqual just tried `v16.9.49` and I cannot reproduce. It's possible this was an issue in the typings from react and not this lib.

**Comment by MarianBe** [comment] 2020-09-16 12:06
I have the same problem. For now i downgraded to `v16.9.43`

**Comment by joelpoloney** [comment] 2020-09-21 01:01
@rolandjitsu can you paste the tsconfig that you're using? Still having this problem. Here's our tsconfig.json that is having this issue:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "noUnusedLocals": true,
    "jsx": "react",
    "lib": ["es2015", "dom", "esnext"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true,
    "pretty": true,
    "removeComments": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "include": ["src", "typings"],
  "exclude": ["node_modules", "build"],
  "types": ["googlemaps"]
}
```

**Comment by rolandjitsu** [comment] 2020-09-22 03:34
> @rolandjitsu can you paste the tsconfig that you're using? Still having this problem. Here's our tsconfig.json that is having this issue (on Typescript v4.0.2):
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es5",
>     "module": "esnext",
>     "moduleResolution": "node",
>     "sourceMap": true,
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "allowJs": true,
>     "noUnusedLocals": true,
>     "jsx": "react",
>     "lib": ["es2015", "dom", "esnext"],
>     "noImplicitAny": true,
>     "suppressImplicitAnyIndexErrors": true,
>     "allowSyntheticDefaultImports": true,
>     "pretty": true,
>     "removeComments": true,
>     "skipLibCheck": true,
>     "esModuleInterop": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true
>   },
>   "include": ["src", "typings"],
>   "exclude": ["node_modules", "build"],
>   "types": ["googlemaps"]
> }
> ```

The config is part of this repo, see [tsconfig.json](https://github.com/react-dropzone/react-dropzone/blob/master/typings/tests/tsconfig.json).

**Comment by joelpoloney** [comment] 2020-10-22 00:53
Has anyone made any progress towards this outside of casting to unknown/any? Still experiencing this with @types/react@16.9.53 and react-dropzone@11.2.0.

**Comment by joelpoloney** [comment] 2020-10-22 01:06
It's possible that this commit: https://github.com/react-dropzone/react-dropzone/commit/aaa9710334a5f28e221cef84c11cf4a013c8c37c#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 will fix it. That upgrades the @types/react to a much more modern release. But it hasn't been released yet. 

@rolandjitsu could we get a patch release (11.2.1) that includes the latest deps upgrade? 🙏

**Comment by rolandjitsu** [comment] 2020-10-22 08:02
@joelpoloney if you find a fix for this we can definitely patch it. Just submit a PR.

**Comment by joelpoloney** [comment] 2020-10-22 15:52
I think you may have already fixed it by upgrading your deps in the commit I referenced above. Any thoughts on when a new release would come out? I think this will fix our problem.

**Comment by rolandjitsu** [comment] 2020-10-23 03:38
> I think you may have already fixed it by upgrading your deps in the commit I referenced above. Any thoughts on when a new release would come out? I think this will fix our problem.

Ok, I see. There's a bunch of PRs in progress that will probably get released soon, so that change will come together with that.

**Comment by joelpoloney** [comment] 2020-10-23 15:32
Just saw the 11.2.1 release but this didn't fix our issue. I'll keep digging.

**Comment by Morteza-Jenabzadeh** [comment] 2020-11-12 08:09
Here is my try without ts yields  error:

    "@types/node": "^12.0.0",
    "@types/react": "^16.9.53",
    "@types/react-dom": "^16.9.8",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-dropzone": "^11.2.4",
    "react-scripts": "4.0.0",
    "typescript": "^4.0.5",
    "web-vitals": "^0.2.4"



```js
import React from 'react'
import {useDropzone} from 'react-dropzone'
const DropZone:React.FC = ()=>{
        const onDrop = React.useCallback(acceptedFiles => {
            // Do something with the files
          }, [])
          const {getRootProps, getInputProps, isDragActive} = useDropzone({onDrop})
    return (
        <div {...getRootProps()}>
        <input {...getInputProps()} />
        {
          isDragActive ?
            <p>Drop the files here ...</p> :
            <p>Drag 'n' drop some files here, or click to select files</p>
        }
      </div>
    )
}
export default DropZone
`

**Comment by ben-dyer** [comment] 2020-11-19 10:13
Not using dropzone, but having a similar issue with react-table and and also styled components. Going back to v16.9.43. also fixed for me

```
    "@types/react": "^16.9.43",
    "@types/react-dom": "^16.9.9",
    "@types/react-table": "^7.0.19",
    "@types/styled-components": "^5.0.1",
    "react": "^17.0.1",
    "react-bootstrap": "^1.3.0",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.0",
    "react-table": "^7.2.2",
    "styled-components": "^5.2.0",
```

Same issue with appearance, but slightly more specifically issue with "button-bevel"

> Type 'import("/path/to/src/node_modules/@types/react-dom/node_modules/@types/react/index").CSSProperties' is not assignable to type 'React.CSSProperties'

>  Types of property 'appearance' are incompatible.
              Type '"button" | "meter" | "textarea" | "none" | "inherit" | "initial" | "radio" | "listbox" | "-moz-initial" | "revert" | "unset" | "button-bevel" | "checkbox" | "menulist" | "menulist-button" | ... 6 more ... | undefined' is not assignable to type '"button" | "meter" | "textarea" | "none" | "auto" | "inherit" | "initial" | "radio" | "listbox" | "-moz-initial" | "revert" | "unset" | "checkbox" | "menulist" | "menulist-button" | ... 6 more ... | undefined'.
                Type '"button-bevel"' is not assignable to type '"button" | "meter" | "textarea" | "none" | "auto" | "inherit" | "initial" | "radio" | "listbox" | "-moz-initial" | "revert" | "unset" | "checkbox" | "menulist" | "menulist-button" | ... 6 more ... | undefined'.

**Comment by rolandjitsu** [comment] 2020-11-22 08:58
Does this happen after `v16.9.46`? Because if it doesn't, I'm not sure how we can fix it from our side.

**Comment by mwarger** [comment] 2020-11-24 19:17
I was able to get around this for now by using this in my input...

```
<input
        {...getInputProps()}
        style={{
          ...getInputProps().style,
          appearance: 'none',
          columnFill: 'balance',
          MozColumnFill: 'balance',
          WebkitColumnFill: 'balance',
        }}
      />
```

**Comment by joelpoloney** [comment] 2020-11-29 17:13
@mwarger's workaround also works for us. @rolandjitsu does that give you any insight into how to fix the problem? It looks like there are 4 properties that don't overlap for some reason.

**Comment by Morteza-Jenabzadeh** [comment] 2020-11-30 05:35
> Does this happen after `v16.9.46`? Because if it doesn't, I'm not sure how we can fix it from our side.

Dosen't happen with `"@types/react": "^16.9.53",

**Comment by rolandjitsu** [comment] 2021-03-26 08:13
Closing this as it doesn't happen with the latest versions of typings.

**Closed by rolandjitsu** 2021-03-26 08:13 UTC

**Comment by eric-burel** [comment] 2021-07-15 09:12
For lost googlers: this usually means you have multiple occurrence of `@types/react` with incompatible versions, either in your app or dependencies such as `react-dropzone` or others.
You can add Yarn resolutions to fix this issue:
```json
  "resolutions": {
    "@types/react": "^17.0.14",
    "@types/react-dom": "^17.0.9"
  }
```

Note: this seems problematic to me that those package comes with this dependency at first, but this seems to happen a lot.

**Comment by izhan** [comment] 2022-11-28 04:43
And to add to above: if fixing versions of `@types/react` doesn't work, make sure they are also using the same versions of `csstype` in package-lock.json
