### ISSUE TITLE
Incorrect isDragAccept and isDragReject values when dragging

### ISSUE THREAD

**Issue by blackr1234** [react-dropzone/react-dropzone#890] opened 2019-10-11 08:56 UTC
**Do you want to request a *feature* or report a *bug*?**

- I found a bug

---

**What is the current behavior?**

I am testing the basic example from the README.md under the project root folder of this GitHub.
No configurations are made.

When I drag a file to the dropzone, before dropping:
- `isDragAccept` is `false`
- `isDragReject` is `true`

Version: `10.1.10`

Web browsers:
- Chrome `68`
- Chromium `77`

Try here:
https://codesandbox.io/s/react-codesandbox-ky27p

---

**What is the expected behavior?**

When I drag a file to the dropzone, before dropping:
- `isDragAccept` should be `true`
- `isDragReject` should be `false`

The values are correct in the previous release version `10.1.9`.

Try here:
https://codesandbox.io/s/react-codesandbox-3en8d

---

Relates to #888

**Comment by blackr1234** [comment] 2019-10-11 09:06
#888

**Comment by wesleyguirra** [comment] 2019-10-11 15:12
same here

**Comment by rolandjitsu** [comment] 2019-10-12 04:50
I think this is a duplicate of https://github.com/react-dropzone/react-dropzone/issues/888.

**Closed by rolandjitsu** 2019-10-12 04:50 UTC

**Comment by parth-r-parmar** [comment] 2022-01-29 05:42
Still having issue in react-dropzone@11.5.3 when i am passing **accept** as ".mp3" or "audio/mp3" and dragging xyz.mp3 file, isDragReject : true

Work as expected if i passed **accept** as "audio/*". But not when **accept**:".mp3"  or  accept:"audio/mp3"
But what if i want only ".mp3" ?

![Screenshot (100)](https://user-images.githubusercontent.com/71545063/151649099-fdbbe14f-a665-4b63-a03d-2724a30b82e9.png)
